// Full site content in 12 languages. Heavy content reuses the same
// professional translations as the multilingual CV; site-UI strings are
// translated here. EN/FR are authored in full; others share the structure.
import { profile, tools, type Experience, type Project, type Education } from "./data";

export type Locale =
  | "en" | "fr" | "es" | "pt" | "de" | "it" | "zh" | "ja" | "ko" | "ru" | "ar" | "hi";

export const locales: { code: Locale; native: string; en: string; dir: "ltr" | "rtl" }[] = [
  { code: "en", native: "English", en: "English", dir: "ltr" },
  { code: "fr", native: "Français", en: "French", dir: "ltr" },
  { code: "es", native: "Español", en: "Spanish", dir: "ltr" },
  { code: "pt", native: "Português", en: "Portuguese", dir: "ltr" },
  { code: "de", native: "Deutsch", en: "German", dir: "ltr" },
  { code: "it", native: "Italiano", en: "Italian", dir: "ltr" },
  { code: "zh", native: "中文", en: "Chinese", dir: "ltr" },
  { code: "ja", native: "日本語", en: "Japanese", dir: "ltr" },
  { code: "ko", native: "한국어", en: "Korean", dir: "ltr" },
  { code: "ru", native: "Русский", en: "Russian", dir: "ltr" },
  { code: "ar", native: "العربية", en: "Arabic", dir: "rtl" },
  { code: "hi", native: "हिन्दी", en: "Hindi", dir: "ltr" },
];

export const localeCodes = locales.map((l) => l.code);
export const isLocale = (x: string): x is Locale => (localeCodes as string[]).includes(x);
export const dirOf = (code: Locale) => locales.find((l) => l.code === code)?.dir ?? "ltr";
export const localePath = (code: Locale, sub = "") =>
  (code === "en" ? "" : `/${code}`) + sub || "/";

export type SiteContent = {
  lang: Locale;
  nav: { experience: string; projects: string; music: string; education: string; contact: string; download: string };
  hero: { availability: string; cvLine: string; title: string; meta: string[]; summary: string; getInTouch: string; downloadCv: string };
  stats: { value: string; label: string }[];
  statsNote: string;
  about: { label: string; title: string; paragraphs: string[] };
  caseStudy: { label: string; tag: string; title: string; rows: { k: string; v: string }[] };
  experience: { label: string; title: string; items: Experience[] };
  projects: { label: string; title: string; items: Project[] };
  music: { label: string; title: string; intro: string; playLabel: string };
  capabilities: {
    label: string; title: string;
    coreLabel: string; core: string[];
    qualitiesLabel: string; qualities: string[];
    languagesLabel: string; languages: { name: string; level: string }[];
    toolsLabel: string; tools: string[];
  };
  education: { label: string; title: string; items: Education[] };
  cta: { label: string; title: string; text: string; button: string };
  footer: { rights: string; sub: string };
  contact: {
    back: string; h1: string; intro: string;
    emailLabel: string; subjectLabel: string; messageLabel: string;
    emailPh: string; subjectPh: string; messagePh: string;
    send: string; sending: string; success: string; another: string; note: string;
    genericError: string; networkError: string; orDirect: string;
    detail: { email: string; phone: string; elsewhere: string; basedIn: string; copy: string; copied: string };
  };
  metaTitleSuffix: string;
};

const NAME = profile.name;
const ORGS = ["Afterlife Events", "Zara, Montréal", "YCC Sleepaway Camp", "JHoops Basketball Camp", "Villa Maria Basketball Team"];
const STAT_VALUES = ["$50K+", "1,500+", "~47%", "600+"];
const LINK = profile.instagram;
const LINKLABEL = profile.instagramLabel;
const cvLine = `${profile.location} / CV 2026`;

type Raw = {
  nav: SiteContent["nav"];
  availability: string;
  title: string;
  meta: string[];
  summary: string;
  getInTouch: string;
  statsLabels: string[];
  statsNote: string;
  aboutLabel: string;
  aboutTitle: string;
  aboutParas: string[];
  caseTag: string;
  caseRows: { k: string; v: string }[];
  expLabel: string;
  expTitle: string;
  roles: string[];
  periods: string[];
  points: string[][];
  projLabel: string;
  projTitle: string;
  projTitles: string[];
  projTags: string[];
  projDescs: string[];
  musicLabel: string;
  musicTitle: string;
  musicIntro: string;
  playLabel: string;
  capLabel: string;
  capTitle: string;
  coreLabel: string;
  core: string[];
  qualitiesLabel: string;
  qualities: string[];
  languagesLabel: string;
  langs: { name: string; level: string }[];
  toolsLabel: string;
  eduLabel: string;
  eduTitle: string;
  schools: string[];
  eduCreds: string[];
  eduDetails: string[];
  ctaLabel: string;
  ctaTitle: string;
  ctaText: string;
  ctaButton: string;
  footerRights: string;
  footerSub: string;
  contact: SiteContent["contact"];
  metaTitleSuffix?: string;
};

function make(code: Locale, r: Raw): SiteContent {
  return {
    lang: code,
    nav: r.nav,
    hero: {
      availability: r.availability,
      cvLine,
      title: r.title,
      meta: r.meta,
      summary: r.summary,
      getInTouch: r.getInTouch,
      downloadCv: r.nav.download,
    },
    stats: r.statsLabels.map((label, i) => ({ value: STAT_VALUES[i], label })),
    statsNote: r.statsNote,
    about: { label: r.aboutLabel, title: r.aboutTitle, paragraphs: r.aboutParas },
    caseStudy: { label: r.aboutLabel, tag: r.caseTag, title: "Afterlife Events", rows: r.caseRows },
    experience: {
      label: r.expLabel,
      title: r.expTitle,
      items: r.roles.map((role, i) => ({ role, org: ORGS[i], period: r.periods[i], points: r.points[i] })),
    },
    projects: {
      label: r.projLabel,
      title: r.projTitle,
      items: [
        { title: r.projTitles[0], tag: r.projTags[0], description: r.projDescs[0], link: LINK, linkLabel: LINKLABEL },
        { title: r.projTitles[1], tag: r.projTags[1], description: r.projDescs[1] },
        { title: r.projTitles[2], tag: r.projTags[2], description: r.projDescs[2] },
      ],
    },
    music: { label: r.musicLabel, title: r.musicTitle, intro: r.musicIntro, playLabel: r.playLabel },
    capabilities: {
      label: r.capLabel,
      title: r.capTitle,
      coreLabel: r.coreLabel,
      core: r.core,
      qualitiesLabel: r.qualitiesLabel,
      qualities: r.qualities,
      languagesLabel: r.languagesLabel,
      languages: r.langs,
      toolsLabel: r.toolsLabel,
      tools,
    },
    education: {
      label: r.eduLabel,
      title: r.eduTitle,
      items: r.schools.map((school, i) => ({ school, credential: r.eduCreds[i], detail: r.eduDetails[i] })),
    },
    cta: { label: r.ctaLabel, title: r.ctaTitle, text: r.ctaText, button: r.ctaButton },
    footer: { rights: r.footerRights, sub: r.footerSub },
    contact: r.contact,
    metaTitleSuffix: r.metaTitleSuffix ?? "",
  };
}

const RAW: Record<Locale, Raw> = {
  en: {
    nav: { experience: "Experience", projects: "Projects", music: "Music", education: "Education", contact: "Contact", download: "Download CV" },
    availability: "Open to new opportunities",
    title: "Bilingual Sales & Business Development",
    meta: ["Founder · Afterlife Events", "Social Science student · Dawson College"],
    summary: profile.summary,
    getInTouch: "Get in touch",
    statsLabels: ["Revenue generated", "Tickets sold", "Profit margin", "Songs mixed"],
    statsNote: "Revenue, tickets, and margin from 5 Afterlife Events shows in under one year.",
    aboutLabel: "About",
    aboutTitle: "The short version",
    aboutParas: [
      "I'm a bilingual Dawson College student who would rather build than wait. I started Afterlife Events with no budget and no audience — just outreach, negotiation, and a lot of follow-up.",
      "In under a year it grew to five events, 1,500+ tickets, and over $50K in revenue at roughly 47% margin, all with zero ad spend. Outside of that I've spent 6+ years as a self-taught mixing engineer and build small web projects on the side. The throughline is the same: spot the opening, do the unglamorous work, and close.",
    ],
    caseTag: "Featured",
    caseRows: [
      { k: "Problem", v: "No budget, no following, and a crowded Montréal nightlife market to break into." },
      { k: "Approach", v: "Cold outreach, organic content, and word of mouth to sell out rooms; negotiated venue, vendor, and sponsorship deals to protect margin; hired and led a team of 10+." },
      { k: "Result", v: "5 events, 1,500+ tickets, and $50K+ in revenue at ~47% margin in under a year — with zero ad spend." },
    ],
    expLabel: "Experience",
    expTitle: "Where I've worked",
    roles: ["Founder", "Retail Associate", "Bunk Counselor", "Camp Counselor", "Team Member, Shooting Guard"],
    periods: ["July 2025 – Present", "July 2025 – August 2025", "July 2024 – August 2024", "July 2023 – August 2023", "October 2019 – March 2020"],
    points: [
      ["Sole founder, generating over $50,000 in revenue at an approximately 47% profit margin across 5 events in under one year.", "Sold 1,500+ tickets with zero ad spend, driving all sales through organic outreach, content, and word of mouth.", "Secured sponsorships and brand partnerships through cold outreach and direct negotiation.", "Built and managed client relationships across thousands of interactions, resolving issues and building a loyal repeat following.", "Negotiated venue and vendor contracts to protect margins.", "Hired and led teams of 10+ while studying full time at Dawson College."],
      ["Served approximately 300 customers per shift on the sales floor in English and French, answering product questions and driving purchase decisions.", "Maintained store organization, restocked merchandise, and kept fitting rooms and displays presentation-ready.", "Worked within a team of 10+ to keep the floor running smoothly during high-traffic periods."],
      ["Supervised a group of approximately 20 children aged 7 to 9 throughout a multi-week residential camp.", "Planned and led daily activities including sports, swimming, and drama.", "Resolved conflicts between campers and supported children experiencing homesickness.", "Coordinated daily routines: meals, hygiene, bedtime, and transitions between activities."],
      ["Supervised mixed-age groups of children aged 6 to 12 throughout the day.", "Designed age-appropriate workouts, games, and activities.", "Made sure every child felt included, engaged, and safe during transitions."],
      ["Committed to a full competitive season while keeping up with school, attending every practice on time.", "Worked closely with teammates toward shared goals under a demanding schedule.", "Built early discipline in time management, balancing practices with academic workload."],
    ],
    projLabel: "Projects / Ventures",
    projTitle: "Things I've built",
    projTitles: ["Afterlife Events", "Audio Engineering", "Technology & Web"],
    projTags: ["Founder · Events", "Self-taught · 6+ years", "Builder · AI tools"],
    projDescs: [
      "A profitable events business I built from scratch: 5 events, 1,500+ tickets, and over $50K in revenue at roughly 47% margin, all with zero ad spend.",
      "Mixing engineer for 6+ years. I've mixed 600+ songs across pop, rap, Afrobeat, and more for paying clients, working in Logic Pro and FL Studio.",
      "I build websites and small apps with AI coding tools like Claude and ChatGPT, and edit videos and montages in Final Cut Pro.",
    ],
    musicLabel: "Music",
    musicTitle: "Mixes I've made",
    musicIntro: "A selection of my mixing work across pop, hip-hop, rock, and electronic, mixed in Logic Pro and FL Studio. Press play.",
    playLabel: "Play",
    capLabel: "Capabilities",
    capTitle: "What I bring",
    coreLabel: "Core skills",
    core: ["Revenue growth", "Negotiation & closing", "Client relationships", "Outreach & prospecting", "Bilingual communication", "Lead generation & marketing"],
    qualitiesLabel: "Qualities",
    qualities: ["Self-driven", "Resilient", "Persuasive", "Results-oriented"],
    languagesLabel: "Languages",
    langs: [{ name: "English", level: "Native" }, { name: "French", level: "Native" }],
    toolsLabel: "Tools & software",
    eduLabel: "Education",
    eduTitle: "Background",
    schools: ["Dawson College, Montréal", "Villa Maria High School, Montréal"],
    eduCreds: ["DEC in Social Science", "High School Diploma"],
    eduDetails: ["Expected May 2026", "2024"],
    ctaLabel: "Contact",
    ctaTitle: "Let's talk",
    ctaText: "Whether it's a role, a project, or an event, I'd like to hear about it. I usually reply within a day.",
    ctaButton: "Contact me",
    footerRights: `© 2026 ${NAME}. All rights reserved.`,
    footerSub: `Open to new opportunities · ${profile.location} · Updated May 2026`,
    contact: {
      back: "← Back to home", h1: "Say hello.",
      intro: "Have an opportunity, question, or idea? Send me a message and it lands straight in my inbox. I usually reply within 24 hours.",
      emailLabel: "Your email", subjectLabel: "Subject", messageLabel: "Message",
      emailPh: "you@example.com", subjectPh: "What's this about?", messagePh: "Write your message here…",
      send: "Send message", sending: "Sending…", success: "Thanks! Your message has been sent. I'll reply within a day.",
      another: "Send another message", note: "I usually reply within a day.",
      genericError: "Something went wrong. Please try again.", networkError: "Network error. Please check your connection and try again.",
      orDirect: "or reach me directly",
      detail: { email: "Email", phone: "Phone", elsewhere: "Elsewhere", basedIn: "Based in", copy: "Copy", copied: "Copied ✓" },
    },
  },

  fr: {
    nav: { experience: "Expérience", projects: "Projets", music: "Musique", education: "Formation", contact: "Contact", download: "Télécharger le CV" },
    availability: "Ouvert aux nouvelles opportunités",
    title: "Ventes bilingues et développement commercial",
    meta: ["Fondateur · Afterlife Events", "Étudiant en sciences humaines · Collège Dawson"],
    summary:
      "Étudiant bilingue au Collège Dawson et fondateur. J'ai bâti une entreprise événementielle rentable à partir de zéro, vendu plus de 1 500 billets et décroché des commandites grâce à la prospection à froid et à la négociation. Je suis à l'aise pour générer des revenus, conclure des ventes et bâtir des relations clients en anglais comme en français.",
    getInTouch: "Prendre contact",
    statsLabels: ["Revenus générés", "Billets vendus", "Marge bénéficiaire", "Chansons mixées"],
    statsNote: "Revenus, billets et marge issus de 5 événements Afterlife en moins d'un an.",
    aboutLabel: "À propos",
    aboutTitle: "En bref",
    aboutParas: [
      "Je suis un étudiant bilingue au Collège Dawson qui préfère bâtir plutôt qu'attendre. J'ai lancé Afterlife Events sans budget ni public — seulement de la prospection, de la négociation et beaucoup de suivi.",
      "En moins d'un an, l'entreprise a atteint cinq événements, plus de 1 500 billets vendus et plus de 50 000 $ de revenus à environ 47 % de marge, sans aucune dépense publicitaire. À côté, je suis ingénieur de mixage autodidacte depuis plus de 6 ans et je crée de petits projets web. Le fil conducteur reste le même : repérer l'occasion, faire le travail ingrat et conclure.",
    ],
    caseTag: "En vedette",
    caseRows: [
      { k: "Problème", v: "Aucun budget, aucune audience et un marché de la vie nocturne montréalaise très concurrentiel à percer." },
      { k: "Approche", v: "Prospection à froid, contenu organique et bouche-à-oreille pour remplir les salles ; négociation des ententes de salles, de fournisseurs et de commandites pour protéger la marge ; recrutement et direction d'une équipe de plus de 10 personnes." },
      { k: "Résultat", v: "5 événements, plus de 1 500 billets et plus de 50 000 $ de revenus à ~47 % de marge en moins d'un an — sans aucune dépense publicitaire." },
    ],
    expLabel: "Expérience",
    expTitle: "Où j'ai travaillé",
    roles: ["Fondateur", "Conseiller de vente", "Moniteur de camp", "Moniteur de camp", "Membre de l'équipe, arrière"],
    periods: ["Juillet 2025 – Présent", "Juillet 2025 – Août 2025", "Juillet 2024 – Août 2024", "Juillet 2023 – Août 2023", "Octobre 2019 – Mars 2020"],
    points: [
      ["Fondateur unique, générant plus de 50 000 $ de revenus avec une marge bénéficiaire d'environ 47 % sur 5 événements en moins d'un an.", "Vendu plus de 1 500 billets sans aucune dépense publicitaire, toutes les ventes provenant de la prospection organique, du contenu et du bouche-à-oreille.", "Obtenu des commandites et des partenariats de marque grâce à la prospection à froid et à la négociation directe.", "Bâti et entretenu des relations clients sur des milliers d'interactions, en résolvant les problèmes et en fidélisant une clientèle récurrente.", "Négocié les contrats de salles et de fournisseurs afin de protéger les marges.", "Recruté et dirigé des équipes de plus de 10 personnes tout en étudiant à temps plein au Collège Dawson."],
      ["Servi environ 300 clients par quart sur la surface de vente, en anglais et en français, en répondant aux questions et en orientant les décisions d'achat.", "Maintenu l'organisation du magasin, réapprovisionné la marchandise et gardé les cabines et les présentoirs impeccables.", "Travaillé au sein d'une équipe de plus de 10 personnes pour assurer le bon fonctionnement du magasin durant les périodes d'affluence."],
      ["Encadré un groupe d'environ 20 enfants âgés de 7 à 9 ans pendant un camp résidentiel de plusieurs semaines.", "Planifié et animé des activités quotidiennes : sports, natation et théâtre.", "Résolu des conflits entre campeurs et soutenu des enfants vivant le mal du pays.", "Coordonné les routines quotidiennes : repas, hygiène, coucher et transitions entre les activités."],
      ["Encadré des groupes d'enfants d'âges variés, de 6 à 12 ans, tout au long de la journée.", "Conçu des entraînements, des jeux et des activités adaptés à chaque âge.", "Veillé à ce que chaque enfant se sente inclus, engagé et en sécurité lors des transitions."],
      ["Engagé pour une saison complète de compétition tout en suivant l'école, présent à chaque entraînement à l'heure.", "Travaillé en étroite collaboration avec mes coéquipiers vers des objectifs communs, malgré un horaire exigeant.", "Développé tôt une discipline de gestion du temps en conciliant les entraînements et la charge scolaire."],
    ],
    projLabel: "Projets",
    projTitle: "Ce que j'ai bâti",
    projTitles: ["Afterlife Events", "Ingénierie audio", "Technologie et web"],
    projTags: ["Fondateur · Événementiel", "Autodidacte · 6+ ans", "Créateur · Outils d'IA"],
    projDescs: [
      "Une entreprise événementielle rentable bâtie de zéro : 5 événements, plus de 1 500 billets et plus de 50 000 $ de revenus à environ 47 % de marge, sans aucune dépense publicitaire.",
      "Ingénieur de mixage depuis plus de 6 ans. J'ai mixé plus de 600 morceaux (pop, rap, Afrobeat et autres) pour des clients payants, sur Logic Pro et FL Studio.",
      "Je crée des sites web et de petites applications avec des outils d'IA comme Claude et ChatGPT, et je monte des vidéos sur Final Cut Pro.",
    ],
    musicLabel: "Musique",
    musicTitle: "Mes mixages",
    musicIntro: "Une sélection de mes mixages en pop, hip-hop, rock et électronique, réalisés sur Logic Pro et FL Studio. Appuyez sur lecture.",
    playLabel: "Lecture",
    capLabel: "Compétences",
    capTitle: "Ce que j'apporte",
    coreLabel: "Compétences clés",
    core: ["Croissance du chiffre d'affaires", "Négociation et conclusion", "Relations clients", "Prospection et démarchage", "Communication bilingue", "Génération de leads et marketing"],
    qualitiesLabel: "Qualités",
    qualities: ["Autonome", "Résilient", "Persuasif", "Orienté résultats"],
    languagesLabel: "Langues",
    langs: [{ name: "Anglais", level: "Langue maternelle" }, { name: "Français", level: "Langue maternelle" }],
    toolsLabel: "Outils et logiciels",
    eduLabel: "Formation",
    eduTitle: "Parcours",
    schools: ["Collège Dawson, Montréal", "École secondaire Villa Maria, Montréal"],
    eduCreds: ["DEC en Sciences humaines", "Diplôme d'études secondaires"],
    eduDetails: ["Prévu mai 2026", "2024"],
    ctaLabel: "Contact",
    ctaTitle: "Parlons-en",
    ctaText: "Un poste, un projet ou un événement ? J'aimerais en entendre parler. Je réponds généralement en moins d'une journée.",
    ctaButton: "Me contacter",
    footerRights: `© 2026 ${NAME}. Tous droits réservés.`,
    footerSub: `Ouvert aux nouvelles opportunités · ${profile.location} · Mis à jour mai 2026`,
    contact: {
      back: "← Retour à l'accueil", h1: "Dites bonjour.",
      intro: "Une opportunité, une question ou une idée ? Envoyez-moi un message, il arrive directement dans ma boîte de réception. Je réponds généralement en moins de 24 heures.",
      emailLabel: "Votre courriel", subjectLabel: "Sujet", messageLabel: "Message",
      emailPh: "vous@exemple.com", subjectPh: "De quoi s'agit-il ?", messagePh: "Écrivez votre message ici…",
      send: "Envoyer le message", sending: "Envoi…", success: "Merci ! Votre message a été envoyé. Je vous réponds en moins d'une journée.",
      another: "Envoyer un autre message", note: "Je réponds généralement en moins d'une journée.",
      genericError: "Une erreur s'est produite. Veuillez réessayer.", networkError: "Erreur réseau. Vérifiez votre connexion et réessayez.",
      orDirect: "ou contactez-moi directement",
      detail: { email: "Courriel", phone: "Téléphone", elsewhere: "Ailleurs", basedIn: "Basé à", copy: "Copier", copied: "Copié ✓" },
    },
  },

  es: {
    nav: { experience: "Experiencia", projects: "Proyectos", music: "Música", education: "Formación", contact: "Contacto", download: "Descargar CV" },
    availability: "Abierto a nuevas oportunidades",
    title: "Ventas bilingües y desarrollo de negocios",
    meta: ["Fundador · Afterlife Events", "Estudiante de Ciencias Sociales · Dawson College"],
    summary:
      "Estudiante bilingüe del Dawson College y fundador. Construí desde cero un negocio de eventos rentable, vendí más de 1.500 entradas y conseguí patrocinios mediante prospección en frío y negociación. Me siento cómodo generando ingresos, cerrando ventas y creando relaciones con clientes tanto en inglés como en francés.",
    getInTouch: "Ponerse en contacto",
    statsLabels: ["Ingresos generados", "Entradas vendidas", "Margen de beneficio", "Canciones mezcladas"],
    statsNote: "Ingresos, entradas y margen de 5 eventos Afterlife en menos de un año.",
    aboutLabel: "Acerca de",
    aboutTitle: "En resumen",
    aboutParas: [
      "Soy un estudiante bilingüe del Dawson College que prefiere construir antes que esperar. Empecé Afterlife Events sin presupuesto ni audiencia: solo prospección, negociación y mucho seguimiento.",
      "En menos de un año creció a cinco eventos, más de 1.500 entradas y más de 50.000 $ en ingresos con cerca del 47 % de margen, todo sin gasto en publicidad. Aparte de eso, llevo más de 6 años como ingeniero de mezcla autodidacta y creo pequeños proyectos web. El hilo conductor es el mismo: detectar la oportunidad, hacer el trabajo ingrato y cerrar.",
    ],
    caseTag: "Destacado",
    caseRows: [
      { k: "Problema", v: "Sin presupuesto, sin audiencia y un mercado nocturno de Montreal muy competitivo en el que entrar." },
      { k: "Enfoque", v: "Prospección en frío, contenido orgánico y boca a boca para llenar las salas; negociación de acuerdos con locales, proveedores y patrocinadores para proteger el margen; contratación y dirección de un equipo de más de 10 personas." },
      { k: "Resultado", v: "5 eventos, más de 1.500 entradas y más de 50.000 $ en ingresos al ~47 % de margen en menos de un año, sin gasto en publicidad." },
    ],
    expLabel: "Experiencia",
    expTitle: "Dónde he trabajado",
    roles: ["Fundador", "Asesor de ventas", "Monitor de campamento", "Monitor de campamento", "Miembro del equipo, escolta"],
    periods: ["Julio 2025 – Presente", "Julio 2025 – Agosto 2025", "Julio 2024 – Agosto 2024", "Julio 2023 – Agosto 2023", "Octubre 2019 – Marzo 2020"],
    points: [
      ["Fundador único, generando más de 50.000 USD en ingresos con un margen de beneficio de aproximadamente el 47 % en 5 eventos en menos de un año.", "Vendí más de 1.500 entradas sin gasto en publicidad, impulsando todas las ventas mediante prospección orgánica, contenido y boca a boca.", "Conseguí patrocinios y alianzas de marca mediante prospección en frío y negociación directa.", "Construí y gestioné relaciones con clientes a lo largo de miles de interacciones, resolviendo problemas y fidelizando una clientela recurrente.", "Negocié contratos con locales y proveedores para proteger los márgenes.", "Contraté y dirigí equipos de más de 10 personas mientras estudiaba a tiempo completo en Dawson College."],
      ["Atendí a unos 300 clientes por turno en la sala de ventas, en inglés y francés, respondiendo preguntas e impulsando las decisiones de compra.", "Mantuve la organización de la tienda, repuse mercancía y dejé los probadores y exhibidores listos.", "Trabajé en un equipo de más de 10 personas para mantener la tienda funcionando durante las horas de mayor afluencia."],
      ["Supervisé a un grupo de unos 20 niños de 7 a 9 años durante un campamento residencial de varias semanas.", "Planifiqué y dirigí actividades diarias como deportes, natación y teatro.", "Resolví conflictos entre campistas y apoyé a niños que extrañaban su hogar.", "Coordiné rutinas diarias: comidas, higiene, hora de dormir y transiciones entre actividades."],
      ["Supervisé grupos de niños de distintas edades, de 6 a 12 años, durante todo el día.", "Diseñé entrenamientos, juegos y actividades adecuados para cada edad.", "Me aseguré de que cada niño se sintiera incluido, motivado y seguro en las transiciones."],
      ["Me comprometí con una temporada competitiva completa mientras cumplía con los estudios, asistiendo puntualmente a cada entrenamiento.", "Trabajé en estrecha colaboración con mis compañeros hacia objetivos comunes bajo un calendario exigente.", "Desarrollé temprano la disciplina de la gestión del tiempo, equilibrando los entrenamientos y la carga académica."],
    ],
    projLabel: "Proyectos",
    projTitle: "Lo que he creado",
    projTitles: ["Afterlife Events", "Ingeniería de audio", "Tecnología y web"],
    projTags: ["Fundador · Eventos", "Autodidacta · 6+ años", "Creador · Herramientas de IA"],
    projDescs: [
      "Un negocio de eventos rentable que construí desde cero: 5 eventos, más de 1.500 entradas y más de 50.000 $ en ingresos a cerca del 47 % de margen, todo sin gasto en publicidad.",
      "Ingeniero de mezcla desde hace más de 6 años. He mezclado más de 600 canciones de pop, rap, Afrobeat y otros géneros para clientes de pago, usando Logic Pro y FL Studio.",
      "Creo sitios web y pequeñas aplicaciones con herramientas de IA como Claude y ChatGPT, y edito vídeos y montajes en Final Cut Pro.",
    ],
    musicLabel: "Música",
    musicTitle: "Mezclas que he hecho",
    musicIntro: "Una selección de mis mezclas en pop, hip-hop, rock y electrónica, hechas en Logic Pro y FL Studio. Dale al play.",
    playLabel: "Reproducir",
    capLabel: "Aptitudes",
    capTitle: "Lo que aporto",
    coreLabel: "Aptitudes clave",
    core: ["Crecimiento de ingresos", "Negociación y cierre", "Relaciones con clientes", "Prospección y captación", "Comunicación bilingüe", "Generación de leads y marketing"],
    qualitiesLabel: "Cualidades",
    qualities: ["Autónomo", "Resiliente", "Persuasivo", "Orientado a resultados"],
    languagesLabel: "Idiomas",
    langs: [{ name: "Inglés", level: "Nativo" }, { name: "Francés", level: "Nativo" }],
    toolsLabel: "Herramientas y software",
    eduLabel: "Formación",
    eduTitle: "Formación",
    schools: ["Dawson College, Montreal", "Escuela Secundaria Villa Maria, Montreal"],
    eduCreds: ["DEC en Ciencias Sociales", "Diploma de secundaria"],
    eduDetails: ["Previsto mayo 2026", "2024"],
    ctaLabel: "Contacto",
    ctaTitle: "Hablemos",
    ctaText: "Ya sea un puesto, un proyecto o un evento, me gustaría conocerlo. Suelo responder en menos de un día.",
    ctaButton: "Contáctame",
    footerRights: `© 2026 ${NAME}. Todos los derechos reservados.`,
    footerSub: `Abierto a nuevas oportunidades · ${profile.location} · Actualizado mayo 2026`,
    contact: {
      back: "← Volver al inicio", h1: "Hola.",
      intro: "¿Tienes una oportunidad, una pregunta o una idea? Envíame un mensaje y llegará directo a mi bandeja. Suelo responder en menos de 24 horas.",
      emailLabel: "Tu correo", subjectLabel: "Asunto", messageLabel: "Mensaje",
      emailPh: "tu@ejemplo.com", subjectPh: "¿De qué se trata?", messagePh: "Escribe tu mensaje aquí…",
      send: "Enviar mensaje", sending: "Enviando…", success: "¡Gracias! Tu mensaje se ha enviado. Te respondo en menos de un día.",
      another: "Enviar otro mensaje", note: "Suelo responder en menos de un día.",
      genericError: "Algo salió mal. Inténtalo de nuevo.", networkError: "Error de red. Comprueba tu conexión e inténtalo de nuevo.",
      orDirect: "o contáctame directamente",
      detail: { email: "Correo", phone: "Teléfono", elsewhere: "En otras partes", basedIn: "Ubicado en", copy: "Copiar", copied: "Copiado ✓" },
    },
  },

  pt: {
    nav: { experience: "Experiência", projects: "Projetos", music: "Música", education: "Formação", contact: "Contato", download: "Baixar CV" },
    availability: "Aberto a novas oportunidades",
    title: "Vendas bilíngue e desenvolvimento de negócios",
    meta: ["Fundador · Afterlife Events", "Estudante de Ciências Sociais · Dawson College"],
    summary:
      "Estudante bilíngue do Dawson College e fundador. Construí do zero um negócio de eventos lucrativo, vendi mais de 1.500 ingressos e consegui patrocínios por meio de prospecção ativa e negociação. Sinto-me à vontade para gerar receita, fechar vendas e construir relacionamentos com clientes em inglês e francês.",
    getInTouch: "Entrar em contato",
    statsLabels: ["Receita gerada", "Ingressos vendidos", "Margem de lucro", "Músicas mixadas"],
    statsNote: "Receita, ingressos e margem de 5 eventos Afterlife em menos de um ano.",
    aboutLabel: "Sobre",
    aboutTitle: "Em resumo",
    aboutParas: [
      "Sou um estudante bilíngue do Dawson College que prefere construir a esperar. Comecei a Afterlife Events sem orçamento e sem público — apenas prospecção, negociação e muito acompanhamento.",
      "Em menos de um ano, cresceu para cinco eventos, mais de 1.500 ingressos e mais de US$ 50 mil em receita a cerca de 47% de margem, tudo sem gasto com anúncios. Além disso, há mais de 6 anos sou engenheiro de mixagem autodidata e crio pequenos projetos web. O fio condutor é o mesmo: enxergar a oportunidade, fazer o trabalho ingrato e fechar.",
    ],
    caseTag: "Em destaque",
    caseRows: [
      { k: "Problema", v: "Sem orçamento, sem audiência e um mercado de vida noturna de Montreal muito concorrido para entrar." },
      { k: "Abordagem", v: "Prospecção ativa, conteúdo orgânico e boca a boca para lotar as casas; negociação de acordos com locais, fornecedores e patrocinadores para proteger a margem; contratação e liderança de uma equipe de mais de 10 pessoas." },
      { k: "Resultado", v: "5 eventos, mais de 1.500 ingressos e mais de US$ 50 mil em receita a ~47% de margem em menos de um ano — sem gasto com anúncios." },
    ],
    expLabel: "Experiência",
    expTitle: "Onde trabalhei",
    roles: ["Fundador", "Consultor de vendas", "Monitor de acampamento", "Monitor de acampamento", "Membro da equipe, ala-armador"],
    periods: ["Julho 2025 – Presente", "Julho 2025 – Agosto 2025", "Julho 2024 – Agosto 2024", "Julho 2023 – Agosto 2023", "Outubro 2019 – Março 2020"],
    points: [
      ["Fundador único, gerando mais de US$ 50.000 em receita com margem de lucro de aproximadamente 47% em 5 eventos em menos de um ano.", "Vendi mais de 1.500 ingressos sem gasto com anúncios, impulsionando todas as vendas por prospecção orgânica, conteúdo e boca a boca.", "Consegui patrocínios e parcerias de marca por meio de prospecção ativa e negociação direta.", "Construí e gerenciei relacionamentos com clientes ao longo de milhares de interações, resolvendo problemas e fidelizando clientes recorrentes.", "Negociei contratos com locais e fornecedores para proteger as margens.", "Contratei e liderei equipes de mais de 10 pessoas enquanto estudava em tempo integral no Dawson College."],
      ["Atendi cerca de 300 clientes por turno no salão de vendas, em inglês e francês, respondendo dúvidas e impulsionando decisões de compra.", "Mantive a organização da loja, repus mercadorias e deixei provadores e vitrines impecáveis.", "Trabalhei em uma equipe de mais de 10 pessoas para manter a loja funcionando nos horários de pico."],
      ["Supervisionei um grupo de cerca de 20 crianças de 7 a 9 anos durante um acampamento residencial de várias semanas.", "Planejei e conduzi atividades diárias, incluindo esportes, natação e teatro.", "Resolvi conflitos entre os campistas e apoiei crianças com saudade de casa.", "Coordenei rotinas diárias: refeições, higiene, hora de dormir e transições entre atividades."],
      ["Supervisionei grupos de crianças de idades variadas, de 6 a 12 anos, ao longo do dia.", "Criei treinos, jogos e atividades adequados a cada idade.", "Garanti que cada criança se sentisse incluída, engajada e segura nas transições."],
      ["Comprometi-me com uma temporada competitiva completa enquanto acompanhava os estudos, chegando pontualmente a cada treino.", "Trabalhei em estreita colaboração com os colegas rumo a objetivos comuns, sob uma agenda exigente.", "Desenvolvi cedo a disciplina de gestão do tempo, conciliando treinos e carga acadêmica."],
    ],
    projLabel: "Projetos",
    projTitle: "O que construí",
    projTitles: ["Afterlife Events", "Engenharia de áudio", "Tecnologia e web"],
    projTags: ["Fundador · Eventos", "Autodidata · 6+ anos", "Criador · Ferramentas de IA"],
    projDescs: [
      "Um negócio de eventos lucrativo que construí do zero: 5 eventos, mais de 1.500 ingressos e mais de US$ 50 mil em receita a cerca de 47% de margem, tudo sem gasto com anúncios.",
      "Engenheiro de mixagem há mais de 6 anos. Já mixei mais de 600 músicas de pop, rap, Afrobeat e outros gêneros para clientes pagantes, usando Logic Pro e FL Studio.",
      "Crio sites e pequenos aplicativos com ferramentas de IA como Claude e ChatGPT, e edito vídeos e montagens no Final Cut Pro.",
    ],
    musicLabel: "Música",
    musicTitle: "Mixagens que fiz",
    musicIntro: "Uma seleção das minhas mixagens em pop, hip-hop, rock e eletrônica, feitas no Logic Pro e FL Studio. Aperte o play.",
    playLabel: "Tocar",
    capLabel: "Competências",
    capTitle: "O que ofereço",
    coreLabel: "Competências principais",
    core: ["Crescimento de receita", "Negociação e fechamento", "Relacionamento com clientes", "Prospecção e captação", "Comunicação bilíngue", "Geração de leads e marketing"],
    qualitiesLabel: "Qualidades",
    qualities: ["Autônomo", "Resiliente", "Persuasivo", "Orientado a resultados"],
    languagesLabel: "Idiomas",
    langs: [{ name: "Inglês", level: "Nativo" }, { name: "Francês", level: "Nativo" }],
    toolsLabel: "Ferramentas e software",
    eduLabel: "Formação",
    eduTitle: "Formação",
    schools: ["Dawson College, Montreal", "Escola Secundária Villa Maria, Montreal"],
    eduCreds: ["DEC em Ciências Sociais", "Diploma do ensino médio"],
    eduDetails: ["Previsto maio 2026", "2024"],
    ctaLabel: "Contato",
    ctaTitle: "Vamos conversar",
    ctaText: "Seja uma vaga, um projeto ou um evento, eu gostaria de saber. Costumo responder em menos de um dia.",
    ctaButton: "Fale comigo",
    footerRights: `© 2026 ${NAME}. Todos os direitos reservados.`,
    footerSub: `Aberto a novas oportunidades · ${profile.location} · Atualizado maio 2026`,
    contact: {
      back: "← Voltar ao início", h1: "Olá.",
      intro: "Tem uma oportunidade, dúvida ou ideia? Envie uma mensagem e ela chega direto na minha caixa de entrada. Costumo responder em menos de 24 horas.",
      emailLabel: "Seu e-mail", subjectLabel: "Assunto", messageLabel: "Mensagem",
      emailPh: "voce@exemplo.com", subjectPh: "Sobre o que é?", messagePh: "Escreva sua mensagem aqui…",
      send: "Enviar mensagem", sending: "Enviando…", success: "Obrigado! Sua mensagem foi enviada. Respondo em menos de um dia.",
      another: "Enviar outra mensagem", note: "Costumo responder em menos de um dia.",
      genericError: "Algo deu errado. Tente novamente.", networkError: "Erro de rede. Verifique sua conexão e tente novamente.",
      orDirect: "ou fale comigo diretamente",
      detail: { email: "E-mail", phone: "Telefone", elsewhere: "Em outros lugares", basedIn: "Sediado em", copy: "Copiar", copied: "Copiado ✓" },
    },
  },

  de: {
    nav: { experience: "Erfahrung", projects: "Projekte", music: "Musik", education: "Ausbildung", contact: "Kontakt", download: "Lebenslauf herunterladen" },
    availability: "Offen für neue Möglichkeiten",
    title: "Zweisprachiger Vertrieb & Business Development",
    meta: ["Gründer · Afterlife Events", "Student der Sozialwissenschaften · Dawson College"],
    summary:
      "Zweisprachiger Student am Dawson College und Gründer. Ich habe ein profitables Eventunternehmen von Grund auf aufgebaut, über 1.500 Tickets verkauft und durch Kaltakquise und Verhandlung Sponsoren gewonnen. Ich generiere souverän Umsatz, schließe Verkäufe ab und baue Kundenbeziehungen auf Englisch und Französisch auf.",
    getInTouch: "Kontakt aufnehmen",
    statsLabels: ["Erzielter Umsatz", "Verkaufte Tickets", "Gewinnmarge", "Gemischte Songs"],
    statsNote: "Umsatz, Tickets und Marge aus 5 Afterlife-Events in weniger als einem Jahr.",
    aboutLabel: "Über mich",
    aboutTitle: "Kurz gefasst",
    aboutParas: [
      "Ich bin ein zweisprachiger Student am Dawson College, der lieber baut als wartet. Ich habe Afterlife Events ohne Budget und ohne Publikum gestartet — nur mit Ansprache, Verhandlung und viel Nachfassen.",
      "In weniger als einem Jahr wuchs es auf fünf Events, über 1.500 Tickets und mehr als 50.000 $ Umsatz bei rund 47 % Marge — ganz ohne Werbebudget. Daneben bin ich seit über 6 Jahren autodidaktischer Mixing-Engineer und baue kleine Web-Projekte. Der rote Faden bleibt gleich: die Chance erkennen, die unglamouröse Arbeit machen und abschließen.",
    ],
    caseTag: "Im Fokus",
    caseRows: [
      { k: "Problem", v: "Kein Budget, keine Reichweite und ein hart umkämpfter Montréaler Nachtleben-Markt, in den es einzutreten galt." },
      { k: "Ansatz", v: "Kaltakquise, organischer Content und Mundpropaganda, um Säle zu füllen; Verhandlung von Verträgen mit Locations, Lieferanten und Sponsoren zum Schutz der Marge; Einstellung und Führung eines Teams von über 10 Personen." },
      { k: "Ergebnis", v: "5 Events, über 1.500 Tickets und mehr als 50.000 $ Umsatz bei ~47 % Marge in weniger als einem Jahr — ohne Werbebudget." },
    ],
    expLabel: "Berufserfahrung",
    expTitle: "Wo ich gearbeitet habe",
    roles: ["Gründer", "Verkaufsmitarbeiter", "Campbetreuer", "Campbetreuer", "Teammitglied, Shooting Guard"],
    periods: ["Juli 2025 – heute", "Juli 2025 – August 2025", "Juli 2024 – August 2024", "Juli 2023 – August 2023", "Oktober 2019 – März 2020"],
    points: [
      ["Alleingründer, über 50.000 $ Umsatz bei rund 47 % Gewinnmarge mit 5 Events in weniger als einem Jahr erzielt.", "Über 1.500 Tickets ohne Werbebudget verkauft, alle Verkäufe durch organische Ansprache, Content und Mundpropaganda erzielt.", "Sponsoren und Markenpartnerschaften durch Kaltakquise und direkte Verhandlung gewonnen.", "Kundenbeziehungen über Tausende Interaktionen aufgebaut und gepflegt, Probleme gelöst und treue Stammkundschaft aufgebaut.", "Verträge mit Veranstaltungsorten und Lieferanten verhandelt, um die Margen zu schützen.", "Teams von über 10 Personen eingestellt und geführt, während ich in Vollzeit am Dawson College studierte."],
      ["Pro Schicht rund 300 Kundinnen und Kunden auf der Verkaufsfläche auf Englisch und Französisch betreut, Produktfragen beantwortet und Kaufentscheidungen gefördert.", "Ladenorganisation gepflegt, Ware aufgefüllt und Umkleiden sowie Auslagen präsentationsbereit gehalten.", "In einem Team von über 10 Personen mitgearbeitet, um den Verkaufsbetrieb in Stoßzeiten reibungslos zu halten."],
      ["Eine Gruppe von rund 20 Kindern im Alter von 7 bis 9 Jahren während eines mehrwöchigen Übernachtungscamps betreut.", "Tägliche Aktivitäten geplant und geleitet, darunter Sport, Schwimmen und Theater.", "Konflikte zwischen Kindern gelöst und Kinder mit Heimweh unterstützt.", "Tagesabläufe koordiniert: Mahlzeiten, Hygiene, Bettzeit und Übergänge zwischen Aktivitäten."],
      ["Altersgemischte Kindergruppen von 6 bis 12 Jahren den ganzen Tag betreut.", "Altersgerechte Trainings, Spiele und Aktivitäten gestaltet.", "Dafür gesorgt, dass sich jedes Kind einbezogen, motiviert und bei Übergängen sicher fühlte."],
      ["Eine ganze Wettkampfsaison absolviert und dabei die Schule gemeistert, pünktlich bei jedem Training.", "Eng mit Teamkollegen auf gemeinsame Ziele hingearbeitet, trotz anspruchsvollem Zeitplan.", "Früh Disziplin im Zeitmanagement entwickelt und Training mit schulischem Pensum vereinbart."],
    ],
    projLabel: "Projekte",
    projTitle: "Was ich gebaut habe",
    projTitles: ["Afterlife Events", "Audio-Engineering", "Technologie & Web"],
    projTags: ["Gründer · Events", "Autodidakt · 6+ Jahre", "Entwickler · KI-Tools"],
    projDescs: [
      "Ein profitables Eventunternehmen, das ich von Grund auf aufgebaut habe: 5 Events, über 1.500 Tickets und mehr als 50.000 $ Umsatz bei rund 47 % Marge — ganz ohne Werbebudget.",
      "Seit über 6 Jahren Mixing-Engineer. Über 600 Songs aus Pop, Rap, Afrobeat und mehr für zahlende Kunden gemischt, mit Logic Pro und FL Studio.",
      "Ich baue Websites und kleine Apps mit KI-Tools wie Claude und ChatGPT und schneide Videos in Final Cut Pro.",
    ],
    musicLabel: "Musik",
    musicTitle: "Meine Mixes",
    musicIntro: "Eine Auswahl meiner Mixing-Arbeit in Pop, Hip-Hop, Rock und Electronic, gemischt in Logic Pro und FL Studio. Drück auf Play.",
    playLabel: "Abspielen",
    capLabel: "Fähigkeiten",
    capTitle: "Was ich mitbringe",
    coreLabel: "Kernkompetenzen",
    core: ["Umsatzwachstum", "Verhandlung & Abschluss", "Kundenbeziehungen", "Akquise & Neukundengewinnung", "Zweisprachige Kommunikation", "Leadgenerierung & Marketing"],
    qualitiesLabel: "Eigenschaften",
    qualities: ["Eigenmotiviert", "Belastbar", "Überzeugend", "Ergebnisorientiert"],
    languagesLabel: "Sprachen",
    langs: [{ name: "Englisch", level: "Muttersprache" }, { name: "Französisch", level: "Muttersprache" }],
    toolsLabel: "Tools & Software",
    eduLabel: "Ausbildung",
    eduTitle: "Werdegang",
    schools: ["Dawson College, Montréal", "Villa Maria High School, Montréal"],
    eduCreds: ["DEC in Sozialwissenschaften", "Hochschulreife (Abitur)"],
    eduDetails: ["Voraussichtlich Mai 2026", "2024"],
    ctaLabel: "Kontakt",
    ctaTitle: "Sprechen wir",
    ctaText: "Ob eine Stelle, ein Projekt oder ein Event — ich höre gern davon. Ich antworte meist innerhalb eines Tages.",
    ctaButton: "Kontaktiere mich",
    footerRights: `© 2026 ${NAME}. Alle Rechte vorbehalten.`,
    footerSub: `Offen für neue Möglichkeiten · ${profile.location} · Aktualisiert Mai 2026`,
    contact: {
      back: "← Zurück zur Startseite", h1: "Sag Hallo.",
      intro: "Eine Gelegenheit, eine Frage oder eine Idee? Schreib mir eine Nachricht — sie landet direkt in meinem Postfach. Ich antworte meist innerhalb von 24 Stunden.",
      emailLabel: "Deine E-Mail", subjectLabel: "Betreff", messageLabel: "Nachricht",
      emailPh: "du@beispiel.com", subjectPh: "Worum geht es?", messagePh: "Schreibe deine Nachricht hier…",
      send: "Nachricht senden", sending: "Senden…", success: "Danke! Deine Nachricht wurde gesendet. Ich antworte innerhalb eines Tages.",
      another: "Weitere Nachricht senden", note: "Ich antworte meist innerhalb eines Tages.",
      genericError: "Etwas ist schiefgelaufen. Bitte versuche es erneut.", networkError: "Netzwerkfehler. Prüfe deine Verbindung und versuche es erneut.",
      orDirect: "oder erreiche mich direkt",
      detail: { email: "E-Mail", phone: "Telefon", elsewhere: "Anderswo", basedIn: "Ansässig in", copy: "Kopieren", copied: "Kopiert ✓" },
    },
  },

  it: {
    nav: { experience: "Esperienza", projects: "Progetti", music: "Musica", education: "Istruzione", contact: "Contatti", download: "Scarica il CV" },
    availability: "Aperto a nuove opportunità",
    title: "Vendite bilingue e sviluppo commerciale",
    meta: ["Fondatore · Afterlife Events", "Studente di Scienze sociali · Dawson College"],
    summary:
      "Studente bilingue al Dawson College e fondatore. Ho creato da zero un'attività di eventi redditizia, venduto oltre 1.500 biglietti e ottenuto sponsorizzazioni tramite contatto a freddo e negoziazione. Mi trovo a mio agio nel generare ricavi, chiudere vendite e costruire relazioni con i clienti sia in inglese che in francese.",
    getInTouch: "Mettiti in contatto",
    statsLabels: ["Ricavi generati", "Biglietti venduti", "Margine di profitto", "Brani mixati"],
    statsNote: "Ricavi, biglietti e margine da 5 eventi Afterlife in meno di un anno.",
    aboutLabel: "Chi sono",
    aboutTitle: "In breve",
    aboutParas: [
      "Sono uno studente bilingue al Dawson College che preferisce costruire piuttosto che aspettare. Ho avviato Afterlife Events senza budget e senza pubblico: solo contatto diretto, negoziazione e tanto follow-up.",
      "In meno di un anno è cresciuto fino a cinque eventi, oltre 1.500 biglietti e più di 50.000 $ di ricavi a circa il 47% di margine, il tutto senza spese pubblicitarie. Oltre a questo, da più di 6 anni sono tecnico del missaggio autodidatta e realizzo piccoli progetti web. Il filo conduttore è lo stesso: cogliere l'occasione, fare il lavoro ingrato e chiudere.",
    ],
    caseTag: "In evidenza",
    caseRows: [
      { k: "Problema", v: "Nessun budget, nessun seguito e un mercato della vita notturna di Montréal molto competitivo in cui entrare." },
      { k: "Approccio", v: "Contatto a freddo, contenuti organici e passaparola per riempire le sale; negoziazione di accordi con sedi, fornitori e sponsor per proteggere il margine; assunzione e guida di un team di oltre 10 persone." },
      { k: "Risultato", v: "5 eventi, oltre 1.500 biglietti e più di 50.000 $ di ricavi al ~47% di margine in meno di un anno — senza spese pubblicitarie." },
    ],
    expLabel: "Esperienza",
    expTitle: "Dove ho lavorato",
    roles: ["Fondatore", "Addetto alle vendite", "Animatore di campo", "Animatore di campo", "Membro della squadra, guardia tiratrice"],
    periods: ["Luglio 2025 – Presente", "Luglio 2025 – Agosto 2025", "Luglio 2024 – Agosto 2024", "Luglio 2023 – Agosto 2023", "Ottobre 2019 – Marzo 2020"],
    points: [
      ["Unico fondatore, oltre 50.000 $ di ricavi con un margine di profitto di circa il 47% su 5 eventi in meno di un anno.", "Venduti oltre 1.500 biglietti senza spese pubblicitarie, generando tutte le vendite tramite contatto organico, contenuti e passaparola.", "Ottenute sponsorizzazioni e partnership di marca tramite contatto a freddo e negoziazione diretta.", "Costruite e gestite relazioni con i clienti su migliaia di interazioni, risolvendo problemi e fidelizzando una clientela ricorrente.", "Negoziati contratti con sedi e fornitori per proteggere i margini.", "Assunti e guidati team di oltre 10 persone studiando a tempo pieno al Dawson College."],
      ["Servito circa 300 clienti per turno in sala vendita, in inglese e francese, rispondendo alle domande e orientando le decisioni d'acquisto.", "Mantenuta l'organizzazione del negozio, rifornita la merce e tenuti camerini ed esposizioni in ordine.", "Lavorato in un team di oltre 10 persone per far funzionare il negozio nei momenti di maggiore affluenza."],
      ["Supervisionato un gruppo di circa 20 bambini dai 7 ai 9 anni durante un campo residenziale di più settimane.", "Pianificate e condotte attività quotidiane tra cui sport, nuoto e teatro.", "Risolti conflitti tra i partecipanti e supportati bambini con nostalgia di casa.", "Coordinate le routine quotidiane: pasti, igiene, ora di dormire e transizioni tra le attività."],
      ["Supervisionati gruppi di bambini di età diverse, dai 6 ai 12 anni, durante la giornata.", "Progettati allenamenti, giochi e attività adatti a ogni età.", "Fatto in modo che ogni bambino si sentisse incluso, coinvolto e al sicuro nelle transizioni."],
      ["Impegnato per un'intera stagione agonistica continuando a studiare, presente puntuale a ogni allenamento.", "Lavorato a stretto contatto con i compagni verso obiettivi comuni, con un calendario impegnativo.", "Sviluppata presto la disciplina nella gestione del tempo, conciliando allenamenti e carico scolastico."],
    ],
    projLabel: "Progetti",
    projTitle: "Cosa ho creato",
    projTitles: ["Afterlife Events", "Ingegneria del suono", "Tecnologia e web"],
    projTags: ["Fondatore · Eventi", "Autodidatta · 6+ anni", "Creatore · Strumenti IA"],
    projDescs: [
      "Un'attività di eventi redditizia creata da zero: 5 eventi, oltre 1.500 biglietti e più di 50.000 $ di ricavi a circa il 47% di margine, il tutto senza spese pubblicitarie.",
      "Tecnico del missaggio da oltre 6 anni. Ho missato più di 600 brani di pop, rap, Afrobeat e altri generi per clienti paganti, usando Logic Pro e FL Studio.",
      "Creo siti web e piccole app con strumenti di IA come Claude e ChatGPT e monto video in Final Cut Pro.",
    ],
    musicLabel: "Musica",
    musicTitle: "I miei mix",
    musicIntro: "Una selezione dei miei missaggi tra pop, hip-hop, rock ed elettronica, realizzati in Logic Pro e FL Studio. Premi play.",
    playLabel: "Riproduci",
    capLabel: "Competenze",
    capTitle: "Cosa offro",
    coreLabel: "Competenze chiave",
    core: ["Crescita dei ricavi", "Negoziazione e chiusura", "Relazioni con i clienti", "Prospezione e acquisizione", "Comunicazione bilingue", "Generazione di lead e marketing"],
    qualitiesLabel: "Qualità",
    qualities: ["Autonomo", "Resiliente", "Persuasivo", "Orientato ai risultati"],
    languagesLabel: "Lingue",
    langs: [{ name: "Inglese", level: "Madrelingua" }, { name: "Francese", level: "Madrelingua" }],
    toolsLabel: "Strumenti e software",
    eduLabel: "Istruzione",
    eduTitle: "Percorso",
    schools: ["Dawson College, Montréal", "Liceo Villa Maria, Montréal"],
    eduCreds: ["DEC in Scienze sociali", "Diploma di scuola superiore"],
    eduDetails: ["Previsto maggio 2026", "2024"],
    ctaLabel: "Contatti",
    ctaTitle: "Parliamone",
    ctaText: "Che si tratti di un ruolo, di un progetto o di un evento, mi piacerebbe saperne di più. Di solito rispondo entro un giorno.",
    ctaButton: "Contattami",
    footerRights: `© 2026 ${NAME}. Tutti i diritti riservati.`,
    footerSub: `Aperto a nuove opportunità · ${profile.location} · Aggiornato maggio 2026`,
    contact: {
      back: "← Torna alla home", h1: "Salve.",
      intro: "Hai un'opportunità, una domanda o un'idea? Inviami un messaggio e arriverà direttamente nella mia casella. Di solito rispondo entro 24 ore.",
      emailLabel: "La tua email", subjectLabel: "Oggetto", messageLabel: "Messaggio",
      emailPh: "tu@esempio.com", subjectPh: "Di cosa si tratta?", messagePh: "Scrivi qui il tuo messaggio…",
      send: "Invia messaggio", sending: "Invio…", success: "Grazie! Il tuo messaggio è stato inviato. Rispondo entro un giorno.",
      another: "Invia un altro messaggio", note: "Di solito rispondo entro un giorno.",
      genericError: "Qualcosa è andato storto. Riprova.", networkError: "Errore di rete. Controlla la connessione e riprova.",
      orDirect: "oppure contattami direttamente",
      detail: { email: "Email", phone: "Telefono", elsewhere: "Altrove", basedIn: "Con sede a", copy: "Copia", copied: "Copiato ✓" },
    },
  },

  zh: {
    nav: { experience: "工作经历", projects: "项目", music: "音乐", education: "教育背景", contact: "联系", download: "下载简历" },
    availability: "欢迎新机会",
    title: "双语销售与业务拓展",
    meta: ["创始人 · Afterlife Events", "社会科学学生 · 道森学院"],
    summary:
      "道森学院双语学生兼创始人。我从零打造了一家盈利的活动策划公司，售出 1,500 多张门票，并通过主动开发和谈判赢得赞助。我能熟练地创造营收、达成销售，并以英语和法语建立客户关系。",
    getInTouch: "联系我",
    statsLabels: ["创造营收", "售出门票", "利润率", "混音歌曲"],
    statsNote: "营收、门票和利润率来自不到一年内的 5 场 Afterlife 活动。",
    aboutLabel: "关于",
    aboutTitle: "简要介绍",
    aboutParas: [
      "我是道森学院的双语学生，比起等待更愿意动手去做。我在没有预算、没有受众的情况下创办了 Afterlife Events——靠的只是主动开发、谈判和大量跟进。",
      "不到一年，它发展到 5 场活动、1,500 多张门票和超过 5 万美元的营收，利润率约 47%，且零广告投入。除此之外，我有 6 年以上自学混音经验，并在业余时间做一些小型网页项目。脉络始终一致：发现机会、做不起眼的苦活、把它谈成。",
    ],
    caseTag: "精选",
    caseRows: [
      { k: "问题", v: "没有预算、没有粉丝，还要打入竞争激烈的蒙特利尔夜生活市场。" },
      { k: "方法", v: "通过主动开发、自然内容和口碑售罄场地；谈判场地、供应商和赞助协议以保护利润；招聘并带领 10 人以上的团队。" },
      { k: "结果", v: "不到一年内 5 场活动、1,500 多张门票、超过 5 万美元营收，利润率约 47%——且零广告投入。" },
    ],
    expLabel: "工作经历",
    expTitle: "工作经历",
    roles: ["创始人", "零售店员", "营地辅导员", "营地辅导员", "球队成员 · 得分后卫"],
    periods: ["2025年7月 – 至今", "2025年7月 – 2025年8月", "2024年7月 – 2024年8月", "2023年7月 – 2023年8月", "2019年10月 – 2020年3月"],
    points: [
      ["唯一创始人，在不到一年内通过 5 场活动创造超过 5 万美元营收，利润率约 47%。", "在零广告投入下售出 1,500 多张门票，全部销售来自自然开发、内容和口碑传播。", "通过主动开发和直接谈判赢得赞助及品牌合作。", "在数千次互动中建立并维护客户关系，解决问题并培养忠实的回头客。", "就场地和供应商合同进行谈判以保护利润。", "在道森学院全日制学习的同时，招聘并带领 10 人以上的团队。"],
      ["每班次以英语和法语服务约 300 名顾客，解答产品问题并促成购买决策。", "保持店面整洁，补货并使试衣间和陈列时刻保持最佳状态。", "在 10 人以上的团队中协作，确保高峰时段店面顺畅运营。"],
      ["在为期数周的住宿营中照护约 20 名 7 至 9 岁的儿童。", "策划并带领每日活动，包括运动、游泳和戏剧。", "化解营员之间的冲突，安抚想家的孩子。", "协调每日作息：用餐、卫生、就寝以及活动间的衔接。"],
      ["全天照护 6 至 12 岁的混龄儿童团体。", "设计适合各年龄段的训练、游戏和活动。", "确保每个孩子在过渡环节都感到被接纳、投入且安全。"],
      ["在兼顾学业的同时投入整个竞技赛季，每次训练都准时到场。", "在紧张的日程下与队友紧密协作，朝着共同目标努力。", "及早养成时间管理的自律，平衡训练与学业负担。"],
    ],
    projLabel: "项目",
    projTitle: "我的作品",
    projTitles: ["Afterlife Events", "音频工程", "技术与网站"],
    projTags: ["创始人 · 活动", "自学 · 6年以上", "构建者 · AI 工具"],
    projDescs: [
      "我从零打造的一家盈利的活动策划公司：5 场活动、1,500 多张门票、超过 5 万美元营收，利润率约 47%，且零广告投入。",
      "拥有 6 年以上混音经验。曾为付费客户混音 600 多首歌曲，涵盖流行、说唱、Afrobeat 等多种风格，使用 Logic Pro 和 FL Studio。",
      "我使用 Claude、ChatGPT 等 AI 编程工具构建网站和小型应用，并用 Final Cut Pro 剪辑视频。",
    ],
    musicLabel: "音乐",
    musicTitle: "我的混音作品",
    musicIntro: "我的混音作品精选，涵盖流行、嘻哈、摇滚和电子，使用 Logic Pro 和 FL Studio 制作。点击播放。",
    playLabel: "播放",
    capLabel: "能力",
    capTitle: "我的能力",
    coreLabel: "核心技能",
    core: ["营收增长", "谈判与成交", "客户关系", "开发与拓客", "双语沟通", "获客与营销"],
    qualitiesLabel: "个人特质",
    qualities: ["自驱力强", "抗压能力强", "有说服力", "结果导向"],
    languagesLabel: "语言",
    langs: [{ name: "英语", level: "母语" }, { name: "法语", level: "母语" }],
    toolsLabel: "工具与软件",
    eduLabel: "教育背景",
    eduTitle: "教育背景",
    schools: ["道森学院，蒙特利尔", "Villa Maria 中学，蒙特利尔"],
    eduCreds: ["社会科学 DEC 文凭", "高中文凭"],
    eduDetails: ["预计 2026 年 5 月", "2024"],
    ctaLabel: "联系方式",
    ctaTitle: "联系我",
    ctaText: "无论是职位、项目还是活动，我都很乐意了解。我通常在一天内回复。",
    ctaButton: "联系我",
    footerRights: `© 2026 ${NAME}。保留所有权利。`,
    footerSub: `欢迎新机会 · ${profile.location} · 更新于 2026 年 5 月`,
    contact: {
      back: "← 返回首页", h1: "你好。",
      intro: "有机会、问题或想法吗？给我留言，它会直接进入我的收件箱。我通常在 24 小时内回复。",
      emailLabel: "你的邮箱", subjectLabel: "主题", messageLabel: "内容",
      emailPh: "you@example.com", subjectPh: "关于什么？", messagePh: "在此输入你的留言…",
      send: "发送消息", sending: "发送中…", success: "谢谢！你的消息已发送。我会在一天内回复。",
      another: "再发一条消息", note: "我通常在一天内回复。",
      genericError: "出错了，请重试。", networkError: "网络错误，请检查连接后重试。",
      orDirect: "或直接联系我",
      detail: { email: "邮箱", phone: "电话", elsewhere: "其他平台", basedIn: "所在地", copy: "复制", copied: "已复制 ✓" },
    },
  },

  ja: {
    nav: { experience: "職務経歴", projects: "プロジェクト", music: "音楽", education: "学歴", contact: "連絡先", download: "履歴書をダウンロード" },
    availability: "新しい機会を歓迎します",
    title: "バイリンガル営業・事業開発",
    meta: ["創業者 · Afterlife Events", "社会科学専攻の学生 · ドーソン・カレッジ"],
    summary:
      "ドーソン・カレッジに通うバイリンガルの学生であり起業家です。ゼロから収益性の高いイベント事業を立ち上げ、1,500 枚以上のチケットを販売し、新規開拓と交渉を通じてスポンサーを獲得しました。英語とフランス語の両方で、売上の創出、商談の成約、顧客との関係構築を得意としています。",
    getInTouch: "お問い合わせ",
    statsLabels: ["創出した売上", "販売チケット", "利益率", "ミックスした楽曲"],
    statsNote: "売上・チケット・利益率は1年未満の5回の Afterlife イベントによるものです。",
    aboutLabel: "プロフィール",
    aboutTitle: "ひとことで言うと",
    aboutParas: [
      "私はドーソン・カレッジに通うバイリンガルの学生で、待つよりもつくる方が好きです。予算もオーディエンスもないところから Afterlife Events を立ち上げました。あったのは開拓と交渉、そして粘り強いフォローだけです。",
      "1年未満で5つのイベント、1,500枚超のチケット、約47%の利益率で5万ドル超の売上にまで成長し、広告費はゼロでした。そのほか、6年以上独学のミキシングエンジニアとして活動し、合間に小規模なウェブ制作も行っています。一貫しているのは、機会を見つけ、地道な作業をこなし、契約をまとめることです。",
    ],
    caseTag: "注目",
    caseRows: [
      { k: "課題", v: "予算もフォロワーもなく、競争の激しいモントリオールのナイトライフ市場に切り込む必要があった。" },
      { k: "アプローチ", v: "新規開拓・オーガニックコンテンツ・口コミで会場を満席に。会場・ベンダー・スポンサーとの契約を交渉し利益率を確保。10名以上のチームを採用・統率。" },
      { k: "結果", v: "1年未満で5イベント、1,500枚超のチケット、約47%の利益率で5万ドル超の売上——広告費ゼロ。" },
    ],
    expLabel: "職務経歴",
    expTitle: "これまでの仕事",
    roles: ["創業者", "販売スタッフ", "キャンプカウンセラー", "キャンプカウンセラー", "チームメンバー（シューティングガード）"],
    periods: ["2025年7月 – 現在", "2025年7月 – 2025年8月", "2024年7月 – 2024年8月", "2023年7月 – 2023年8月", "2019年10月 – 2020年3月"],
    points: [
      ["唯一の創業者として、1 年未満で 5 つのイベントから 5 万ドル超の売上を、約 47% の利益率で達成。", "広告費ゼロで 1,500 枚以上のチケットを販売し、すべての販売をオーガニックな開拓・コンテンツ・口コミで実現。", "新規開拓と直接交渉を通じてスポンサーとブランド提携を獲得。", "数千回のやり取りを通じて顧客関係を構築・維持し、問題を解決してリピーターを獲得。", "利益率を守るため、会場やベンダーとの契約を交渉。", "ドーソン・カレッジでフルタイムで学びながら、10 名以上のチームを採用・統率。"],
      ["1 シフトあたり約 300 名の顧客を英語とフランス語で接客し、商品の質問に答え購入を後押し。", "店舗の整理整頓、商品補充、試着室やディスプレイを常に整えた状態に維持。", "10 名以上のチームで連携し、混雑時も売場を円滑に運営。"],
      ["数週間の宿泊型キャンプで、7〜9 歳の約 20 名の子どもを担当。", "スポーツ、水泳、演劇など日々のアクティビティを企画・運営。", "参加者間の対立を解決し、ホームシックの子どもを支援。", "食事・衛生・就寝・活動間の移行など、日々のルーティンを調整。"],
      ["6〜12 歳の異年齢の子どもグループを一日を通じて担当。", "年齢に合ったトレーニング、ゲーム、アクティビティを設計。", "移行の場面でもすべての子どもが受け入れられ、楽しく安全だと感じられるよう配慮。"],
      ["学業と両立しながらシーズンを通して競技に取り組み、毎回の練習に遅れず参加。", "厳しいスケジュールの中、共通の目標に向けてチームメイトと緊密に連携。", "練習と学業を両立し、早くから時間管理の自律を身につけた。"],
    ],
    projLabel: "プロジェクト",
    projTitle: "つくってきたもの",
    projTitles: ["Afterlife Events", "オーディオエンジニアリング", "テクノロジー・ウェブ"],
    projTags: ["創業者 · イベント", "独学 · 6年以上", "ビルダー · AIツール"],
    projDescs: [
      "ゼロから立ち上げた収益性の高いイベント事業：5 イベント、1,500 枚超のチケット、約 47% の利益率で 5 万ドル超の売上——広告費ゼロ。",
      "6 年以上のミキシングエンジニア経験。Logic Pro と FL Studio を使い、ポップ、ラップ、Afrobeat など 600 曲以上を有料クライアント向けにミックスしてきました。",
      "Claude や ChatGPT などの AI コーディングツールでウェブサイトや小規模アプリを制作し、Final Cut Pro で動画編集も行います。",
    ],
    musicLabel: "音楽",
    musicTitle: "制作したミックス",
    musicIntro: "ポップ、ヒップホップ、ロック、エレクトロニックにわたる私のミキシング作品から。Logic Pro と FL Studio で制作。再生してみてください。",
    playLabel: "再生",
    capLabel: "スキル",
    capTitle: "私の強み",
    coreLabel: "主なスキル",
    core: ["売上成長", "交渉・クロージング", "顧客関係", "新規開拓", "バイリンガルコミュニケーション", "リード獲得・マーケティング"],
    qualitiesLabel: "強み",
    qualities: ["自走力", "レジリエンス", "説得力", "成果志向"],
    languagesLabel: "言語",
    langs: [{ name: "英語", level: "ネイティブ" }, { name: "フランス語", level: "ネイティブ" }],
    toolsLabel: "ツール・ソフト",
    eduLabel: "学歴",
    eduTitle: "学歴",
    schools: ["ドーソン・カレッジ、モントリオール", "ヴィラ・マリア高校、モントリオール"],
    eduCreds: ["社会科学 DEC（準学士相当）", "高校卒業"],
    eduDetails: ["2026年5月修了予定", "2024"],
    ctaLabel: "連絡先",
    ctaTitle: "話しましょう",
    ctaText: "職種、プロジェクト、イベントなど、ぜひお聞かせください。通常1日以内に返信します。",
    ctaButton: "連絡する",
    footerRights: `© 2026 ${NAME}. 全著作権所有。`,
    footerSub: `新しい機会を歓迎します · ${profile.location} · 2026年5月更新`,
    contact: {
      back: "← ホームに戻る", h1: "こんにちは。",
      intro: "機会・ご質問・アイデアがあれば、メッセージをお送りください。私の受信箱に直接届きます。通常24時間以内に返信します。",
      emailLabel: "メールアドレス", subjectLabel: "件名", messageLabel: "メッセージ",
      emailPh: "you@example.com", subjectPh: "ご用件は？", messagePh: "ここにメッセージを入力…",
      send: "メッセージを送信", sending: "送信中…", success: "ありがとうございます！メッセージを送信しました。1日以内に返信します。",
      another: "別のメッセージを送る", note: "通常1日以内に返信します。",
      genericError: "問題が発生しました。もう一度お試しください。", networkError: "ネットワークエラーです。接続を確認して再度お試しください。",
      orDirect: "または直接ご連絡ください",
      detail: { email: "メール", phone: "電話", elsewhere: "その他", basedIn: "拠点", copy: "コピー", copied: "コピー済み ✓" },
    },
  },

  ko: {
    nav: { experience: "경력", projects: "프로젝트", music: "음악", education: "학력", contact: "연락처", download: "이력서 다운로드" },
    availability: "새로운 기회에 열려 있음",
    title: "이중 언어 영업 및 사업 개발",
    meta: ["창업자 · Afterlife Events", "사회과학 전공 학생 · 도슨 칼리지"],
    summary:
      "도슨 칼리지에 재학 중인 이중 언어 구사 학생이자 창업가입니다. 수익성 있는 이벤트 사업을 맨손으로 일궈 1,500장 이상의 티켓을 판매했고, 콜드 아웃리치와 협상을 통해 후원을 유치했습니다. 영어와 프랑스어 모두로 매출 창출, 영업 성사, 고객 관계 구축에 능숙합니다.",
    getInTouch: "연락하기",
    statsLabels: ["창출한 매출", "판매 티켓", "이익률", "믹싱한 곡"],
    statsNote: "매출, 티켓, 이익률은 1년이 안 되는 기간의 5개 Afterlife 행사 기준입니다.",
    aboutLabel: "소개",
    aboutTitle: "한눈에 보기",
    aboutParas: [
      "저는 도슨 칼리지에 재학 중인 이중 언어 구사 학생으로, 기다리기보다 직접 만드는 편입니다. 예산도 팬도 없이 Afterlife Events를 시작했고, 가진 것은 콜드 아웃리치와 협상, 그리고 끈질긴 팔로업뿐이었습니다.",
      "1년이 채 안 되어 행사 5개, 티켓 1,500장 이상, 약 47% 이익률로 5만 달러 이상의 매출로 성장했으며 광고비는 전혀 쓰지 않았습니다. 그 외에도 6년 넘게 독학으로 믹싱 엔지니어로 활동하며 틈틈이 작은 웹 프로젝트를 만듭니다. 일관된 흐름은 같습니다. 기회를 포착하고, 화려하지 않은 일을 해내며, 성사시키는 것입니다.",
    ],
    caseTag: "주요 사례",
    caseRows: [
      { k: "문제", v: "예산도 팔로워도 없고, 경쟁이 치열한 몬트리올 나이트라이프 시장에 진입해야 했습니다." },
      { k: "접근", v: "콜드 아웃리치, 오가닉 콘텐츠, 입소문으로 객석을 매진시켰고, 마진을 지키기 위해 장소·공급업체·후원 계약을 협상했으며, 10명 이상의 팀을 채용하고 이끌었습니다." },
      { k: "결과", v: "1년이 채 안 되어 행사 5개, 티켓 1,500장 이상, 약 47% 이익률로 5만 달러 이상의 매출 — 광고비 0." },
    ],
    expLabel: "경력",
    expTitle: "경력",
    roles: ["창업자", "판매 직원", "캠프 카운슬러", "캠프 카운슬러", "팀원 · 슈팅 가드"],
    periods: ["2025년 7월 – 현재", "2025년 7월 – 2025년 8월", "2024년 7월 – 2024년 8월", "2023년 7월 – 2023년 8월", "2019년 10월 – 2020년 3월"],
    points: [
      ["단독 창업자로서 1년이 채 안 되어 5개 행사에서 약 47% 이익률로 5만 달러 이상의 매출을 달성.", "광고비 없이 티켓 1,500장 이상을 판매했으며, 모든 판매는 오가닉 아웃리치·콘텐츠·입소문으로 달성.", "콜드 아웃리치와 직접 협상을 통해 후원과 브랜드 파트너십을 유치.", "수천 건의 상호작용을 통해 고객 관계를 구축·관리하고, 문제를 해결하며 충성 단골을 확보.", "마진을 지키기 위해 장소 및 공급업체 계약을 협상.", "도슨 칼리지에서 풀타임으로 공부하면서 10명 이상의 팀을 채용하고 이끎."],
      ["교대근무마다 약 300명의 고객을 영어와 프랑스어로 응대하며 제품 문의에 답하고 구매 결정을 유도.", "매장 정리, 상품 보충, 탈의실과 디스플레이를 항상 깔끔하게 유지.", "10명 이상의 팀에서 협업하여 혼잡 시간대에도 매장이 원활히 운영되도록 함."],
      ["수 주간의 숙박형 캠프에서 7~9세 아동 약 20명을 지도.", "스포츠, 수영, 연극 등 매일의 활동을 기획하고 진행.", "캠프 참가자 간 갈등을 해결하고 향수병을 겪는 아이들을 지원.", "식사, 위생, 취침, 활동 간 전환 등 일과를 조율."],
      ["하루 종일 6~12세의 다양한 연령대 아동 그룹을 지도.", "연령에 맞는 운동, 게임, 활동을 기획.", "전환 시간에도 모든 아이가 소속감과 참여감, 안전을 느끼도록 함."],
      ["학업을 병행하며 한 시즌 전체를 소화했고, 모든 훈련에 정시 참석.", "빡빡한 일정 속에서 공동의 목표를 위해 팀원들과 긴밀히 협력.", "훈련과 학업을 병행하며 시간 관리의 자기 규율을 일찍 길렀음."],
    ],
    projLabel: "프로젝트",
    projTitle: "내가 만든 것",
    projTitles: ["Afterlife Events", "오디오 엔지니어링", "기술 · 웹"],
    projTags: ["창업자 · 이벤트", "독학 · 6년 이상", "빌더 · AI 도구"],
    projDescs: [
      "맨손으로 일군 수익성 있는 이벤트 사업: 행사 5개, 티켓 1,500장 이상, 약 47% 이익률로 5만 달러 이상의 매출 — 광고비 0.",
      "6년 이상의 믹싱 엔지니어 경력. Logic Pro와 FL Studio로 팝, 랩, 아프로비트 등 600곡 이상을 유료 클라이언트를 위해 믹싱했습니다.",
      "Claude, ChatGPT 같은 AI 코딩 도구로 웹사이트와 소규모 앱을 만들고, Final Cut Pro로 영상을 편집합니다.",
    ],
    musicLabel: "음악",
    musicTitle: "내가 만든 믹스",
    musicIntro: "팝, 힙합, 록, 일렉트로닉을 아우르는 제 믹싱 작업 모음입니다. Logic Pro와 FL Studio로 작업했습니다. 재생해 보세요.",
    playLabel: "재생",
    capLabel: "역량",
    capTitle: "내가 가진 역량",
    coreLabel: "핵심 역량",
    core: ["매출 성장", "협상 및 클로징", "고객 관계", "신규 개발 및 영업", "이중 언어 커뮤니케이션", "리드 생성 및 마케팅"],
    qualitiesLabel: "강점",
    qualities: ["자기주도적", "회복탄력성", "설득력", "성과 지향"],
    languagesLabel: "언어",
    langs: [{ name: "영어", level: "원어민" }, { name: "프랑스어", level: "원어민" }],
    toolsLabel: "도구 및 소프트웨어",
    eduLabel: "학력",
    eduTitle: "학력",
    schools: ["도슨 칼리지, 몬트리올", "빌라 마리아 고등학교, 몬트리올"],
    eduCreds: ["사회과학 DEC", "고등학교 졸업"],
    eduDetails: ["2026년 5월 취득 예정", "2024"],
    ctaLabel: "연락처",
    ctaTitle: "이야기해요",
    ctaText: "채용, 프로젝트, 행사 무엇이든 듣고 싶습니다. 보통 하루 안에 답장드립니다.",
    ctaButton: "연락하기",
    footerRights: `© 2026 ${NAME}. 모든 권리 보유.`,
    footerSub: `새로운 기회에 열려 있음 · ${profile.location} · 2026년 5월 업데이트`,
    contact: {
      back: "← 홈으로 돌아가기", h1: "안녕하세요.",
      intro: "기회, 질문, 아이디어가 있으신가요? 메시지를 보내주시면 제 받은편지함으로 바로 도착합니다. 보통 24시간 이내에 답장드립니다.",
      emailLabel: "이메일", subjectLabel: "제목", messageLabel: "메시지",
      emailPh: "you@example.com", subjectPh: "어떤 내용인가요?", messagePh: "여기에 메시지를 작성하세요…",
      send: "메시지 보내기", sending: "보내는 중…", success: "감사합니다! 메시지가 전송되었습니다. 하루 안에 답장드릴게요.",
      another: "다른 메시지 보내기", note: "보통 하루 안에 답장드립니다.",
      genericError: "문제가 발생했습니다. 다시 시도해 주세요.", networkError: "네트워크 오류입니다. 연결을 확인하고 다시 시도해 주세요.",
      orDirect: "또는 직접 연락하기",
      detail: { email: "이메일", phone: "전화", elsewhere: "다른 채널", basedIn: "거주지", copy: "복사", copied: "복사됨 ✓" },
    },
  },

  ru: {
    nav: { experience: "Опыт", projects: "Проекты", music: "Музыка", education: "Образование", contact: "Контакты", download: "Скачать резюме" },
    availability: "Открыт к новым возможностям",
    title: "Двуязычные продажи и развитие бизнеса",
    meta: ["Основатель · Afterlife Events", "Студент социальных наук · Колледж Dawson"],
    summary:
      "Двуязычный студент колледжа Dawson и основатель. Я с нуля построил прибыльный бизнес по организации мероприятий, продал более 1 500 билетов и привлёк спонсоров благодаря холодным контактам и переговорам. Уверенно генерирую доход, закрываю продажи и выстраиваю отношения с клиентами на английском и французском языках.",
    getInTouch: "Связаться",
    statsLabels: ["Сгенерированная выручка", "Продано билетов", "Маржа прибыли", "Сведено треков"],
    statsNote: "Выручка, билеты и маржа по 5 мероприятиям Afterlife менее чем за год.",
    aboutLabel: "О себе",
    aboutTitle: "Коротко о себе",
    aboutParas: [
      "Я двуязычный студент колледжа Dawson, который предпочитает действовать, а не ждать. Я запустил Afterlife Events без бюджета и без аудитории — были только холодные контакты, переговоры и упорные напоминания.",
      "Менее чем за год проект вырос до пяти мероприятий, более 1 500 билетов и свыше 50 000 $ выручки при марже около 47 %, и всё это без затрат на рекламу. Помимо этого, я более 6 лет занимаюсь сведением как самоучка и делаю небольшие веб-проекты. Логика всегда одна: увидеть возможность, сделать неблагодарную работу и закрыть сделку.",
    ],
    caseTag: "В центре внимания",
    caseRows: [
      { k: "Задача", v: "Без бюджета, без аудитории и с необходимостью пробиться на насыщенный рынок ночной жизни Монреаля." },
      { k: "Подход", v: "Холодные контакты, органический контент и сарафанное радио для полных залов; переговоры по площадкам, поставщикам и спонсорам для защиты маржи; найм и руководство командой более 10 человек." },
      { k: "Результат", v: "5 мероприятий, более 1 500 билетов и свыше 50 000 $ выручки при марже ~47 % менее чем за год — без затрат на рекламу." },
    ],
    expLabel: "Опыт работы",
    expTitle: "Где я работал",
    roles: ["Основатель", "Продавец-консультант", "Вожатый лагеря", "Вожатый лагеря", "Игрок команды, атакующий защитник"],
    periods: ["Июль 2025 – настоящее время", "Июль 2025 – Август 2025", "Июль 2024 – Август 2024", "Июль 2023 – Август 2023", "Октябрь 2019 – Март 2020"],
    points: [
      ["Единственный основатель: более 50 000 $ выручки при марже около 47 % на 5 мероприятиях менее чем за год.", "Продал более 1 500 билетов без затрат на рекламу, обеспечив все продажи за счёт органического охвата, контента и сарафанного радио.", "Привлёк спонсоров и бренд-партнёрства за счёт холодных контактов и прямых переговоров.", "Выстроил и поддерживал отношения с клиентами в тысячах взаимодействий, решал вопросы и формировал лояльную постоянную аудиторию.", "Вёл переговоры по договорам с площадками и поставщиками для защиты маржи.", "Нанимал и руководил командами более 10 человек, обучаясь на дневном отделении колледжа Dawson."],
      ["Обслуживал около 300 клиентов за смену в торговом зале на английском и французском, отвечал на вопросы и помогал с выбором.", "Поддерживал порядок в магазине, пополнял товар и держал примерочные и витрины в идеальном виде.", "Работал в команде более 10 человек, обеспечивая бесперебойную работу зала в часы пик."],
      ["Курировал группу из примерно 20 детей 7–9 лет в течение многонедельного лагеря с проживанием.", "Планировал и проводил ежедневные занятия: спорт, плавание и театр.", "Разрешал конфликты между детьми и поддерживал тех, кто скучал по дому.", "Координировал распорядок дня: питание, гигиену, отбой и переходы между занятиями."],
      ["Курировал разновозрастные группы детей 6–12 лет в течение дня.", "Разрабатывал тренировки, игры и занятия с учётом возраста.", "Следил за тем, чтобы каждый ребёнок чувствовал себя принятым, вовлечённым и в безопасности."],
      ["Отыграл полный соревновательный сезон, совмещая с учёбой и не пропуская тренировки.", "Тесно работал с командой ради общих целей в условиях напряжённого графика.", "Рано выработал дисциплину тайм-менеджмента, совмещая тренировки и учебную нагрузку."],
    ],
    projLabel: "Проекты",
    projTitle: "Что я создал",
    projTitles: ["Afterlife Events", "Звукорежиссура", "Технологии и веб"],
    projTags: ["Основатель · Мероприятия", "Самоучка · 6+ лет", "Разработчик · ИИ-инструменты"],
    projDescs: [
      "Прибыльный бизнес мероприятий, построенный с нуля: 5 мероприятий, более 1 500 билетов и свыше 50 000 $ выручки при марже около 47 % — без затрат на рекламу.",
      "Сведение более 6 лет. Свёл более 600 треков в жанрах поп, рэп, Afrobeat и других для платных клиентов в Logic Pro и FL Studio.",
      "Создаю сайты и небольшие приложения с помощью ИИ-инструментов, таких как Claude и ChatGPT, и монтирую видео в Final Cut Pro.",
    ],
    musicLabel: "Музыка",
    musicTitle: "Мои миксы",
    musicIntro: "Подборка моих миксов в жанрах поп, хип-хоп, рок и электроника, сведённых в Logic Pro и FL Studio. Нажмите воспроизведение.",
    playLabel: "Слушать",
    capLabel: "Навыки",
    capTitle: "Что я предлагаю",
    coreLabel: "Ключевые навыки",
    core: ["Рост выручки", "Переговоры и закрытие сделок", "Отношения с клиентами", "Поиск и привлечение клиентов", "Двуязычная коммуникация", "Лидогенерация и маркетинг"],
    qualitiesLabel: "Качества",
    qualities: ["Самостоятельный", "Стрессоустойчивый", "Убедительный", "Ориентирован на результат"],
    languagesLabel: "Языки",
    langs: [{ name: "Английский", level: "Родной" }, { name: "Французский", level: "Родной" }],
    toolsLabel: "Инструменты и ПО",
    eduLabel: "Образование",
    eduTitle: "Образование",
    schools: ["Колледж Dawson, Монреаль", "Средняя школа Villa Maria, Монреаль"],
    eduCreds: ["DEC по социальным наукам", "Аттестат о среднем образовании"],
    eduDetails: ["Ожидается в мае 2026", "2024"],
    ctaLabel: "Контакты",
    ctaTitle: "Давайте поговорим",
    ctaText: "Будь то вакансия, проект или мероприятие — буду рад услышать. Обычно отвечаю в течение дня.",
    ctaButton: "Связаться",
    footerRights: `© 2026 ${NAME}. Все права защищены.`,
    footerSub: `Открыт к новым возможностям · ${profile.location} · Обновлено в мае 2026`,
    contact: {
      back: "← На главную", h1: "Здравствуйте.",
      intro: "Есть возможность, вопрос или идея? Напишите мне — сообщение придёт прямо в мой почтовый ящик. Обычно отвечаю в течение 24 часов.",
      emailLabel: "Ваш email", subjectLabel: "Тема", messageLabel: "Сообщение",
      emailPh: "you@example.com", subjectPh: "О чём речь?", messagePh: "Напишите ваше сообщение здесь…",
      send: "Отправить сообщение", sending: "Отправка…", success: "Спасибо! Ваше сообщение отправлено. Отвечу в течение дня.",
      another: "Отправить ещё одно сообщение", note: "Обычно отвечаю в течение дня.",
      genericError: "Что-то пошло не так. Попробуйте ещё раз.", networkError: "Ошибка сети. Проверьте подключение и попробуйте снова.",
      orDirect: "или свяжитесь со мной напрямую",
      detail: { email: "Email", phone: "Телефон", elsewhere: "В сети", basedIn: "Город", copy: "Копировать", copied: "Скопировано ✓" },
    },
  },

  ar: {
    nav: { experience: "الخبرة", projects: "المشاريع", music: "الموسيقى", education: "التعليم", contact: "تواصل", download: "تحميل السيرة الذاتية" },
    availability: "منفتح على فرص جديدة",
    title: "مبيعات ثنائية اللغة وتطوير الأعمال",
    meta: ["مؤسس · Afterlife Events", "طالب علوم اجتماعية · كلية داوسون"],
    summary:
      "طالب ثنائي اللغة في كلية داوسون ومؤسس أعمال. بنيتُ شركة فعاليات مربحة من الصفر، وبِعتُ أكثر من 1500 تذكرة، وحصلتُ على رعايات عبر التواصل المباشر والتفاوض. أجيد تحقيق الإيرادات وإتمام المبيعات وبناء علاقات مع العملاء باللغتين الإنجليزية والفرنسية.",
    getInTouch: "تواصل معي",
    statsLabels: ["الإيرادات المحققة", "التذاكر المباعة", "هامش الربح", "الأغاني الممزوجة"],
    statsNote: "الإيرادات والتذاكر والهامش من 5 فعاليات Afterlife في أقل من عام.",
    aboutLabel: "نبذة",
    aboutTitle: "باختصار",
    aboutParas: [
      "أنا طالب ثنائي اللغة في كلية داوسون أفضّل البناء على الانتظار. أطلقتُ Afterlife Events دون ميزانية ولا جمهور — فقط بالتواصل المباشر والتفاوض والكثير من المتابعة.",
      "في أقل من عام نمت إلى خمس فعاليات، وأكثر من 1500 تذكرة، وأكثر من 50,000 دولار من الإيرادات بهامش يقارب 47%، دون أي إنفاق إعلاني. إلى جانب ذلك، أعمل مهندس مزج صوتي عصاميًا منذ أكثر من 6 سنوات وأبني مشاريع ويب صغيرة. الخيط المشترك واحد: اكتشاف الفرصة، وأداء العمل غير اللامع، وإتمام الصفقة.",
    ],
    caseTag: "مميّز",
    caseRows: [
      { k: "التحدي", v: "لا ميزانية ولا متابعين، وسوق حياة ليلية شديد التنافس في مونتريال يجب اختراقه." },
      { k: "المقاربة", v: "تواصل مباشر ومحتوى عضوي وكلمة شفهية لملء القاعات؛ التفاوض على عقود القاعات والموردين والرعاة لحماية الهامش؛ توظيف وقيادة فريق من أكثر من 10 أشخاص." },
      { k: "النتيجة", v: "5 فعاليات وأكثر من 1500 تذكرة وأكثر من 50,000 دولار من الإيرادات بهامش ~47% في أقل من عام — دون أي إنفاق إعلاني." },
    ],
    expLabel: "الخبرة",
    expTitle: "أين عملت",
    roles: ["مؤسس", "موظف مبيعات", "مشرف مخيم", "مشرف مخيم", "عضو فريق · حارس هجومي"],
    periods: ["يوليو 2025 – حتى الآن", "يوليو 2025 – أغسطس 2025", "يوليو 2024 – أغسطس 2024", "يوليو 2023 – أغسطس 2023", "أكتوبر 2019 – مارس 2020"],
    points: [
      ["المؤسس الوحيد، حقّقتُ أكثر من 50,000 دولار من الإيرادات بهامش ربح يقارب 47% عبر 5 فعاليات في أقل من عام.", "بِعتُ أكثر من 1,500 تذكرة دون أي إنفاق إعلاني، معتمدًا في كل المبيعات على التواصل العضوي والمحتوى والتوصيات الشفهية.", "حصلتُ على رعايات وشراكات علامات تجارية عبر التواصل المباشر والتفاوض.", "بنيتُ وأدرتُ علاقات مع العملاء عبر آلاف التفاعلات، محلًّا للمشكلات وبانيًا قاعدة عملاء أوفياء.", "تفاوضتُ على عقود القاعات والموردين للحفاظ على هوامش الربح.", "وظّفتُ وقدتُ فرقًا من أكثر من 10 أشخاص أثناء دراستي بدوام كامل في كلية داوسون."],
      ["خدمتُ نحو 300 عميل في كل وردية على أرض المبيعات بالإنجليزية والفرنسية، مجيبًا عن الأسئلة وداعمًا لقرارات الشراء.", "حافظتُ على تنظيم المتجر، وأعدتُ تعبئة البضائع، وأبقيتُ غرف القياس والعروض جاهزة.", "عملتُ ضمن فريق من أكثر من 10 أشخاص لضمان سير العمل بسلاسة في أوقات الذروة."],
      ["أشرفتُ على مجموعة من نحو 20 طفلًا بين 7 و9 سنوات طوال مخيم إقامة استمر عدة أسابيع.", "خطّطتُ وقدتُ أنشطة يومية تشمل الرياضة والسباحة والمسرح.", "حللتُ الخلافات بين المشاركين ودعمتُ الأطفال الذين يشعرون بالحنين إلى المنزل.", "نسّقتُ الروتين اليومي: الوجبات والنظافة والنوم والانتقال بين الأنشطة."],
      ["أشرفتُ على مجموعات من أطفال بأعمار متفاوتة من 6 إلى 12 عامًا طوال اليوم.", "صمّمتُ تمارين وألعابًا وأنشطة مناسبة لكل عمر.", "حرصتُ على أن يشعر كل طفل بالانتماء والمشاركة والأمان أثناء الانتقالات."],
      ["التزمتُ بموسم تنافسي كامل مع مواصلة الدراسة، حاضرًا في كل تدريب في وقته.", "عملتُ عن قرب مع زملائي نحو أهداف مشتركة ضمن جدول صعب.", "اكتسبتُ مبكرًا انضباط إدارة الوقت موازنًا بين التدريبات والعبء الدراسي."],
    ],
    projLabel: "المشاريع",
    projTitle: "ما الذي بنيته",
    projTitles: ["Afterlife Events", "هندسة الصوت", "التقنية والويب"],
    projTags: ["مؤسس · فعاليات", "عصامي · 6+ سنوات", "صانع · أدوات ذكاء اصطناعي"],
    projDescs: [
      "شركة فعاليات مربحة بنيتُها من الصفر: 5 فعاليات وأكثر من 1500 تذكرة وأكثر من 50,000 دولار من الإيرادات بهامش يقارب 47% — دون أي إنفاق إعلاني.",
      "مهندس مزج صوتي منذ أكثر من 6 سنوات. مزجتُ أكثر من 600 أغنية في البوب والراب والأفروبيت وغيرها لعملاء مدفوعين باستخدام Logic Pro وFL Studio.",
      "أبني مواقع وتطبيقات صغيرة باستخدام أدوات الذكاء الاصطناعي مثل Claude وChatGPT، وأحرّر مقاطع الفيديو في Final Cut Pro.",
    ],
    musicLabel: "الموسيقى",
    musicTitle: "أعمال المزج التي أنجزتها",
    musicIntro: "مختارات من أعمالي في المزج عبر البوب والهيب هوب والروك والإلكترونيك، مُنجَزة في Logic Pro وFL Studio. اضغط للتشغيل.",
    playLabel: "تشغيل",
    capLabel: "المهارات",
    capTitle: "ما الذي أقدّمه",
    coreLabel: "المهارات الأساسية",
    core: ["نمو الإيرادات", "التفاوض وإتمام الصفقات", "علاقات العملاء", "التنقيب عن العملاء", "تواصل ثنائي اللغة", "توليد العملاء المحتملين والتسويق"],
    qualitiesLabel: "الصفات",
    qualities: ["مبادر ذاتيًا", "مرن", "مقنع", "موجّه نحو النتائج"],
    languagesLabel: "اللغات",
    langs: [{ name: "الإنجليزية", level: "لغة أم" }, { name: "الفرنسية", level: "لغة أم" }],
    toolsLabel: "الأدوات والبرامج",
    eduLabel: "التعليم",
    eduTitle: "الخلفية",
    schools: ["كلية داوسون، مونتريال", "مدرسة فيلا ماريا الثانوية، مونتريال"],
    eduCreds: ["دبلوم DEC في العلوم الاجتماعية", "شهادة الثانوية العامة"],
    eduDetails: ["متوقع مايو 2026", "2024"],
    ctaLabel: "تواصل",
    ctaTitle: "لنتحدث",
    ctaText: "سواء كان منصبًا أو مشروعًا أو فعالية، يسعدني أن أسمع عنه. أردّ عادةً خلال يوم واحد.",
    ctaButton: "تواصل معي",
    footerRights: `© 2026 ${NAME}. جميع الحقوق محفوظة.`,
    footerSub: `منفتح على فرص جديدة · ${profile.location} · تحديث مايو 2026`,
    contact: {
      back: "← العودة إلى الرئيسية", h1: "مرحبًا.",
      intro: "هل لديك فرصة أو سؤال أو فكرة؟ أرسل لي رسالة وستصل مباشرة إلى بريدي. أردّ عادةً خلال 24 ساعة.",
      emailLabel: "بريدك الإلكتروني", subjectLabel: "الموضوع", messageLabel: "الرسالة",
      emailPh: "you@example.com", subjectPh: "عن ماذا؟", messagePh: "اكتب رسالتك هنا…",
      send: "إرسال الرسالة", sending: "جارٍ الإرسال…", success: "شكرًا! تم إرسال رسالتك. سأردّ خلال يوم واحد.",
      another: "إرسال رسالة أخرى", note: "أردّ عادةً خلال يوم واحد.",
      genericError: "حدث خطأ ما. حاول مرة أخرى.", networkError: "خطأ في الشبكة. تحقق من اتصالك وحاول مجددًا.",
      orDirect: "أو تواصل معي مباشرة",
      detail: { email: "البريد", phone: "الهاتف", elsewhere: "منصات أخرى", basedIn: "المقر", copy: "نسخ", copied: "تم النسخ ✓" },
    },
  },

  hi: {
    nav: { experience: "अनुभव", projects: "परियोजनाएँ", music: "संगीत", education: "शिक्षा", contact: "संपर्क", download: "सीवी डाउनलोड करें" },
    availability: "नए अवसरों के लिए तैयार",
    title: "द्विभाषी बिक्री और व्यवसाय विकास",
    meta: ["संस्थापक · Afterlife Events", "सामाजिक विज्ञान का छात्र · डॉसन कॉलेज"],
    summary:
      "डॉसन कॉलेज का द्विभाषी छात्र और संस्थापक। मैंने शून्य से एक लाभदायक इवेंट व्यवसाय खड़ा किया, 1,500+ टिकट बेचे, और कोल्ड आउटरीच व बातचीत के ज़रिए प्रायोजन हासिल किए। मैं अंग्रेज़ी और फ़्रेंच दोनों में राजस्व अर्जित करने, बिक्री पूरी करने और ग्राहक संबंध बनाने में सहज हूँ।",
    getInTouch: "संपर्क करें",
    statsLabels: ["अर्जित राजस्व", "बिके टिकट", "लाभ मार्जिन", "मिक्स किए गाने"],
    statsNote: "राजस्व, टिकट और मार्जिन एक साल से कम में 5 Afterlife आयोजनों से।",
    aboutLabel: "परिचय",
    aboutTitle: "संक्षेप में",
    aboutParas: [
      "मैं डॉसन कॉलेज का द्विभाषी छात्र हूँ जो इंतज़ार करने से बेहतर बनाना पसंद करता है। मैंने Afterlife Events को बिना बजट और बिना दर्शकों के शुरू किया — सिर्फ़ आउटरीच, बातचीत और लगातार फ़ॉलो-अप के दम पर।",
      "एक साल से कम में यह पाँच आयोजनों, 1,500+ टिकटों और 50,000 डॉलर से अधिक राजस्व तक पहुँचा, लगभग 47% मार्जिन के साथ, और वह भी बिना किसी विज्ञापन खर्च के। इसके अलावा मैं 6+ वर्षों से स्व-शिक्षित मिक्सिंग इंजीनियर हूँ और छोटे वेब प्रोजेक्ट बनाता हूँ। मूल बात वही है: अवसर पहचानो, बिना चमक-दमक वाला काम करो, और सौदा पक्का करो।",
    ],
    caseTag: "विशेष",
    caseRows: [
      { k: "समस्या", v: "न बजट, न फ़ॉलोअर्स, और घुसने के लिए मॉन्ट्रियल का भीड़भाड़ वाला नाइटलाइफ़ बाज़ार।" },
      { k: "दृष्टिकोण", v: "हॉल भरने के लिए कोल्ड आउटरीच, ऑर्गेनिक कंटेंट और माउथ-पब्लिसिटी; मार्जिन बचाने के लिए वेन्यू, वेंडर और प्रायोजन सौदों पर बातचीत; 10+ लोगों की टीम को नियुक्त करना और नेतृत्व करना।" },
      { k: "परिणाम", v: "एक साल से कम में 5 आयोजन, 1,500+ टिकट और 50,000 डॉलर से अधिक राजस्व, ~47% मार्जिन पर — बिना किसी विज्ञापन खर्च के।" },
    ],
    expLabel: "अनुभव",
    expTitle: "मैंने कहाँ काम किया",
    roles: ["संस्थापक", "रिटेल असोसिएट", "कैंप काउंसलर", "कैंप काउंसलर", "टीम सदस्य · शूटिंग गार्ड"],
    periods: ["जुलाई 2025 – वर्तमान", "जुलाई 2025 – अगस्त 2025", "जुलाई 2024 – अगस्त 2024", "जुलाई 2023 – अगस्त 2023", "अक्टूबर 2019 – मार्च 2020"],
    points: [
      ["एकमात्र संस्थापक, एक साल से कम समय में 5 आयोजनों से लगभग 47% लाभ मार्जिन के साथ 50,000 डॉलर से अधिक राजस्व अर्जित किया।", "बिना किसी विज्ञापन खर्च के 1,500+ टिकट बेचे, सभी बिक्री ऑर्गेनिक आउटरीच, कंटेंट और माउथ-पब्लिसिटी से की।", "कोल्ड आउटरीच और सीधी बातचीत के ज़रिए प्रायोजन और ब्रांड साझेदारियाँ हासिल कीं।", "हज़ारों इंटरैक्शन के दौरान ग्राहक संबंध बनाए और संभाले, समस्याएँ सुलझाईं और वफ़ादार दोहराने वाले ग्राहक तैयार किए।", "मार्जिन सुरक्षित रखने के लिए वेन्यू और वेंडर अनुबंधों पर बातचीत की।", "डॉसन कॉलेज में फुल-टाइम पढ़ाई करते हुए 10+ लोगों की टीमों को नियुक्त किया और नेतृत्व किया।"],
      ["हर शिफ्ट में लगभग 300 ग्राहकों को अंग्रेज़ी और फ़्रेंच में सेवा दी, उत्पाद संबंधी सवालों के जवाब दिए और खरीद निर्णयों को बढ़ावा दिया।", "स्टोर की व्यवस्था बनाए रखी, सामान दोबारा भरा, और फिटिंग रूम व डिस्प्ले हमेशा तैयार रखे।", "व्यस्त समय में स्टोर सुचारू रूप से चलाने के लिए 10+ लोगों की टीम के साथ काम किया।"],
      ["कई हफ़्तों के आवासीय शिविर में 7 से 9 वर्ष के लगभग 20 बच्चों की देखरेख की।", "खेल, तैराकी और नाटक सहित रोज़ाना की गतिविधियाँ योजनाबद्ध कीं और संचालित कीं।", "शिविरार्थियों के बीच झगड़े सुलझाए और घर की याद करने वाले बच्चों को सहारा दिया।", "रोज़ का क्रम संभाला: भोजन, स्वच्छता, सोने का समय और गतिविधियों के बीच बदलाव।"],
      ["दिनभर 6 से 12 वर्ष के मिश्रित आयु वर्ग के बच्चों की देखरेख की।", "हर आयु के अनुरूप वर्कआउट, खेल और गतिविधियाँ तैयार कीं।", "हर बच्चे को बदलावों के दौरान शामिल, सक्रिय और सुरक्षित महसूस कराया।"],
      ["पढ़ाई के साथ-साथ पूरे प्रतिस्पर्धी सीज़न में हिस्सा लिया, हर अभ्यास में समय पर उपस्थित रहा।", "कठिन कार्यक्रम के बावजूद साझा लक्ष्यों के लिए साथियों के साथ मिलकर काम किया।", "अभ्यास और पढ़ाई में संतुलन बनाकर समय-प्रबंधन का अनुशासन जल्दी विकसित किया।"],
    ],
    projLabel: "परियोजनाएँ",
    projTitle: "मैंने क्या बनाया",
    projTitles: ["Afterlife Events", "ऑडियो इंजीनियरिंग", "तकनीक और वेब"],
    projTags: ["संस्थापक · इवेंट्स", "स्व-शिक्षित · 6+ वर्ष", "बिल्डर · AI टूल्स"],
    projDescs: [
      "शून्य से बनाया गया लाभदायक इवेंट व्यवसाय: 5 आयोजन, 1,500+ टिकट और 50,000 डॉलर से अधिक राजस्व, ~47% मार्जिन पर — बिना किसी विज्ञापन खर्च के।",
      "6+ साल से मिक्सिंग इंजीनियर। मैंने Logic Pro और FL Studio में पॉप, रैप, Afrobeat आदि के 600+ गाने पेड क्लाइंट्स के लिए मिक्स किए हैं।",
      "मैं Claude और ChatGPT जैसे AI कोडिंग टूल्स से वेबसाइट और छोटे ऐप बनाता हूँ, और Final Cut Pro में वीडियो एडिट करता हूँ।",
    ],
    musicLabel: "संगीत",
    musicTitle: "मेरे बनाए मिक्स",
    musicIntro: "पॉप, हिप-हॉप, रॉक और इलेक्ट्रॉनिक में मेरे मिक्सिंग काम का चयन, Logic Pro और FL Studio में बनाया गया। प्ले दबाएँ।",
    playLabel: "चलाएँ",
    capLabel: "योग्यताएँ",
    capTitle: "मैं क्या लाता हूँ",
    coreLabel: "मुख्य कौशल",
    core: ["राजस्व वृद्धि", "बातचीत और सौदा पक्का करना", "ग्राहक संबंध", "आउटरीच और प्रॉस्पेक्टिंग", "द्विभाषी संचार", "लीड जनरेशन और मार्केटिंग"],
    qualitiesLabel: "विशेषताएँ",
    qualities: ["स्व-प्रेरित", "लचीला", "प्रेरक", "परिणाम-उन्मुख"],
    languagesLabel: "भाषाएँ",
    langs: [{ name: "अंग्रेज़ी", level: "मातृभाषा" }, { name: "फ़्रेंच", level: "मातृभाषा" }],
    toolsLabel: "टूल्स और सॉफ़्टवेयर",
    eduLabel: "शिक्षा",
    eduTitle: "पृष्ठभूमि",
    schools: ["डॉसन कॉलेज, मॉन्ट्रियल", "विला मारिया हाई स्कूल, मॉन्ट्रियल"],
    eduCreds: ["सामाजिक विज्ञान में DEC", "हाई स्कूल डिप्लोमा"],
    eduDetails: ["मई 2026 अपेक्षित", "2024"],
    ctaLabel: "संपर्क",
    ctaTitle: "बात करते हैं",
    ctaText: "चाहे कोई भूमिका हो, प्रोजेक्ट हो या इवेंट, मैं उसके बारे में सुनना चाहूँगा। मैं आमतौर पर एक दिन में जवाब देता हूँ।",
    ctaButton: "मुझसे संपर्क करें",
    footerRights: `© 2026 ${NAME}. सर्वाधिकार सुरक्षित।`,
    footerSub: `नए अवसरों के लिए तैयार · ${profile.location} · मई 2026 को अपडेट किया गया`,
    contact: {
      back: "← होम पर वापस", h1: "नमस्ते।",
      intro: "कोई अवसर, प्रश्न या विचार है? मुझे संदेश भेजें, यह सीधे मेरे इनबॉक्स में पहुँचेगा। मैं आमतौर पर 24 घंटे में जवाब देता हूँ।",
      emailLabel: "आपका ईमेल", subjectLabel: "विषय", messageLabel: "संदेश",
      emailPh: "you@example.com", subjectPh: "किस बारे में?", messagePh: "अपना संदेश यहाँ लिखें…",
      send: "संदेश भेजें", sending: "भेजा जा रहा है…", success: "धन्यवाद! आपका संदेश भेज दिया गया है। मैं एक दिन में जवाब दूँगा।",
      another: "एक और संदेश भेजें", note: "मैं आमतौर पर एक दिन में जवाब देता हूँ।",
      genericError: "कुछ गड़बड़ हो गई। कृपया फिर से प्रयास करें।", networkError: "नेटवर्क त्रुटि। कृपया अपना कनेक्शन जाँचें और पुनः प्रयास करें।",
      orDirect: "या मुझसे सीधे संपर्क करें",
      detail: { email: "ईमेल", phone: "फ़ोन", elsewhere: "अन्य जगह", basedIn: "स्थित", copy: "कॉपी", copied: "कॉपी हो गया ✓" },
    },
  },
};

export const content = Object.fromEntries(
  localeCodes.map((c) => [c, make(c, RAW[c])])
) as Record<Locale, SiteContent>;
